### ISSUE TITLE
sdk fails to build with latest cyw43-driver

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-sdk#1000]
In file included from /home/peterh/source/pico/pico-sdk/lib/cyw43-driver/src/cyw43_ll.c:40:
/home/peterh/source/pico/pico-sdk/lib/cyw43-driver/src/cyw43_config.h:51:39: fatal error: firmware/wifi_nvram_43439.h: No such file or directory
   51 | #define CYW43_WIFI_NVRAM_INCLUDE_FILE "firmware/wifi_nvram_43439.h"

**Comment by kilograham** [comment]
merged into develop
