### ISSUE TITLE
Need a method cyw43_hal_get_mac_ascii for mDns

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-sdk#1010]
The code in micropython for mDns adds a few characters of the mac address to the host name which makes sense. The function to do this doesn't exist in the SDK.

With this I can then open a url in a browser http://picow1a28.local/

**Comment by lurch** [comment]
Nice. My inkjet printer also does something similar, giving it the hostname http://HP579096.local/

**Comment by peterharperuk** [comment]
Ah - it must be some sort of "standard".

**Comment by lurch** [comment]
I believe the `.local` part is part of the MDNS standard, but using (part of) the ASCII-version of the MAC address is _probably_ just the easiest way to get a guaranteed-reasonably-unique-id on embedded hardware? :shrug:

**Comment by peterharperuk** [comment]
closing this - agreed it's not an sdk issue
