### ISSUE TITLE
getchar_timeout_us() sleeps in increments of 1ms

### ISSUE THREAD

**Issue by lowfatcode** [raspberrypi/pico-sdk#1014]
The parameter and function name suggest much finer granularity than the implementation allows!

**Comment by kilograham** [comment]
um, what?

https://github.com/raspberrypi/pico-sdk/blob/2e6142b15b8a75c1227dd3edbe839193b2bf9041/src/rp2_common/pico_stdio/stdio.c#L143

**Comment by kilograham** [comment]
closing as i think you are mistaken. re-open otherwise
