### ISSUE TITLE
Add lwip/TinyUSB docs to the SDK docs

### ISSUE THREAD

**Issue by kilograham** [raspberrypi/pico-sdk#1031]
We now include Doxygen from `cyw43_driver`; we should try to add TinyUSB and lwip also (though given how fickle Doxygen is, i don't know whether we can do this directly as part of our main doxygen pass)

**Comment by kilograham** [comment]
actually we should just link to their documentation site since we are HTML anyway

**Comment by aallan** [comment]
Just an FYI. We're in the process of integrating the Pico SDK API directly into the documentation site, see https://github.com/raspberrypi/documentation/pull/2743 for details, and will be spinning down the existing micro-site.

**Comment by lurch** [comment]
...although we'll want to keep the Doxygen build "working", as that's used by the PR Alasdair mentioned, and we'll also be keeping the "Appendix E: Building the SDK API documentation" in https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf

**Comment by kilograham** [comment]
yeah what i meant was that rather than trying to batch include the documentation somehow as part of our tree, we'll put links to their documentation sites in the relevant places in our docs.

**Comment by aallan** [comment]
Yup. Got it!

A taster of what things should look like at the top level.

![image](https://user-images.githubusercontent.com/53625/216089318-9c0ae630-b6cc-4ddf-8435-5aca9ac54cd9.png)

**Comment by kilograham** [comment]
fixed by #1220

**Comment by kilograham** [comment]
merged into develop
