### ISSUE TITLE
stdout_serialize_begin can cause a deadlock

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-sdk#1039]
See https://github.com/georgerobotics/cyw43-driver/issues/33

**Comment by kilograham** [comment]
Ok, so the problem here is interaction of two different mutexes:

core 0 is doing plain getchar() which takes stdio_usb mutex but **not** printf mutex.

core 1 does printf that takes printf mutex, then fails to take stdio_usb_mutex

core 0 IRQ does printf, which tries to take printf mutex

**Comment by kilograham** [comment]
merged into develop
