### ISSUE TITLE
[hardware_watchdog] add "missing" watchdog_disable() 

### ISSUE THREAD

**Issue by tjko** [raspberrypi/pico-sdk#1045]
Currently SDK doesn't provide a way do disable watchdog after it's been enabled using _watchdog_enable()_.

Please consider adding _"watchdog_disable()"_ to easily disable watchdog. 

Maybe something along the lines:
```
void watchdog_disable()
{
        hw_clear_bits(&watchdog_hw->ctrl, WATCHDOG_CTRL_ENABLE_BITS);
}

```

**Comment by peterharperuk** [comment]
watchdog_disable has been added
