### ISSUE TITLE
Pico W cyw43_arch_wifi_connect_timeout_ms gives up before timeout

### ISSUE THREAD

**Issue by MrGreensWorkshop** [raspberrypi/pico-sdk#1054]
### Problem
Pico W cyw43_arch_wifi_connect_timeout_ms gives up before timeout.

### Expected behavior
Calling cyw43_arch_wifi_connect_timeout_ms is expected to try to connect to wifi within the given timeout.

### Steps to reproduce:
1. Make sure your AP is turned off. (you can use smartphone hotspot AP too)
2. Plug Raspberry Pi Pico W to USB.
3. After 5 second, Turn your AP on.

### Test code
I created test code to check cyw43_arch_wifi_connect_timeout_ms function behavior. [Full project](https://github.com/raspberrypi/pico-sdk/files/10067783/RasPiPicoSDK_wifi_con_test-main.zip)(on macOS open in VS Code run ./build.sh)

```C
#include <stdio.h>

#include "pico/stdlib.h"
#include "pico/cyw43_arch.h"

char ssid[] = "A Network";
char pass[] = "A Password";
const uint32_t timeout = 1000 * 60 * 10;// 10min

int main() {
    stdio_init_all();

    if (cyw43_arch_init_with_country(CYW43_COUNTRY_UK)) {
        printf("failed to initialise\n");
        return 1;
    }
    printf("initialised\n");

    cyw43_arch_enable_sta_mode();

    int ret = cyw43_arch_wifi_connect_timeout_ms(ssid, pass, CYW43_AUTH_WPA2_AES_PSK, timeout);
    if (ret) {
        printf("failed to connect, resp: %d\n", ret);
        return 1;
    }

    printf("connected\n");
}
```
if AP is there at the beginning, It connects within 10 secs.

### Log
```
connect status: joining
connect status: no ip
connect status: link up
connected
```

if AP isn't there at the beginning It fails within 10 secs .
```
connect status: joining
connect status: network fail
failed to connect, resp: -2
```
`PICO_ERROR_GENERIC = -2 `

### Conclusion
This is how it's called. (I'm sure you already know it)

https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_cyw43_arch/cyw43_arch.c

```
cyw43_arch_wifi_connect_timeout_ms -> cyw43_arch_wifi_connect_until -> 
{
   cyw43_arch_wifi_connect_async -> called once
   checks link status with cyw43_tcpip_link_status and cyw43_arch_poll
}
```

I think the way its checking connection is wrong. 

Since link fails, I think, cyw43_arch_wifi_connect_async must be called again periodically.

this could be related to #917 but I'm not sure.

**Comment by MrGreensWorkshop** [comment]
I think suggested error codes for cyw43_arch_wifi_connect_timeout_ms misleading.

[Documentation](https://raspberrypi.github.io/pico-sdk-doxygen/group__pico__cyw43__arch.html#gae1237b71f7793ba603a4b39da37c7a71) suggests, See also -> **pico_error_codes**
I think these are the right ones in [cyw43.h](https://github.com/georgerobotics/cyw43-driver/blob/195dfcc10bb6f379e3dea45147590db2203d3c7b/src/cyw43.h#L80)

#define CYW43_LINK_DOWN         (0)     ///< link is down
#define CYW43_LINK_JOIN         (1)     ///< Connected to wifi
#define CYW43_LINK_NOIP         (2)     ///< Connected to wifi, but no IP address
#define CYW43_LINK_UP           (3)     ///< Connect to wifi with an IP address
#define CYW43_LINK_FAIL         (-1)    ///< Connection failed
#define CYW43_LINK_NONET        (-2)    ///< No matching SSID found (could be out of range, or down)
#define CYW43_LINK_BADAUTH      (-3)    ///< Authenticatation failure

**Comment by MrGreensWorkshop** [comment]
I think suggested error codes for **cyw43_arch_wifi_connect_timeout_ms** is misleading.

[Documentation](https://raspberrypi.github.io/pico-sdk-doxygen/group__pico__cyw43__arch.html#gae1237b71f7793ba603a4b39da37c7a71) suggests, See also -> [**pico_error_codes**](https://raspberrypi.github.io/pico-sdk-doxygen/group__pico__base.html#gaddcb20bc9a61ceff479aa87369a862aa)

```C
enum pico_error_codes {
  PICO_OK = 0 , 
  PICO_ERROR_NONE = 0 , 
  PICO_ERROR_TIMEOUT = -1 , 
  PICO_ERROR_GENERIC = -2 ,
  PICO_ERROR_NO_DATA = -3 , 
  PICO_ERROR_NOT_PERMITTED = -4 , 
  PICO_ERROR_INVALID_ARG = -5 , 
  PICO_ERROR_IO = -6
}
```

I think these are the right ones from [cyw43.h](https://github.com/georgerobotics/cyw43-driver/blob/195dfcc10bb6f379e3dea45147590db2203d3c7b/src/cyw43.h#L80)
I mean, return value of **cyw43_arch_wifi_connect_until** can be **PICO_OK**, **PICO_ERROR_TIMEOUT** or one of these below.


```C
#define CYW43_LINK_DOWN         (0)     ///< link is down
#define CYW43_LINK_JOIN         (1)     ///< Connected to wifi
#define CYW43_LINK_NOIP         (2)     ///< Connected to wifi, but no IP address
#define CYW43_LINK_UP           (3)     ///< Connect to wifi with an IP address
#define CYW43_LINK_FAIL         (-1)    ///< Connection failed
#define CYW43_LINK_NONET        (-2)    ///< No matching SSID found (could be out of range, or down)
#define CYW43_LINK_BADAUTH      (-3)    ///< Authenticatation failure
```

in this case it is **CYW43_LINK_NONET**

**Comment by peterharperuk** [comment]
> I mean, return value of [cyw43_arch_wifi_connect_until](https://github.com/raspberrypi/pico-sdk/blob/2e6142b15b8a75c1227dd3edbe839193b2bf9041/src/rp2_common/pico_cyw43_arch/cyw43_arch.c#L73) can be PICO_OK, PICO_ERROR_TIMEOUT or one of these below.

or CYW43_EPERM  or CYW43_EIO

**Comment by peterharperuk** [comment]
After making this change, cyw43_arch_wifi_connect_blocking could potentially never return. I wonder if that's a problem

**Comment by kilograham** [comment]
^ note we should either return CYW43_ errors or PICO_ erros, but not a mixture of both

**Comment by MrGreensWorkshop** [comment]
@peterharperuk Thanks for the fix. I didn't test it, but it looks fine.

The only place that PICO_errors used is, cyw43_arch_wifi_connect_until (PICO_ERROR_TIMEOUT) in `cyw43_arch.c/h` I agree with @kilograham, that mixing things up can be confusing. I prefer to have a time-out error in CYW43_ errors to avoid confusion. 

Also, `see pico_error_codes` in `cyw43_arch.h` file needs to be fixed for other functions too.

I believe documentation is generated with doxygen, it will be fixed automatically.

**Comment by peterharperuk** [comment]
> The only place that PICO_errors used is, cyw43_arch_wifi_connect_until

cyw43_arch_wifi_connect_until calls cyw43_arch_wifi_connect_async which returns pico_error_codes.

> there is no way to tell where those are coming from

CYW43_EPERM or CYW43_EIO are defines used in the cyw43-driver that are set to pico_error_codes. The cyw43-driver is used by other platforms.

**Comment by peterharperuk** [comment]
I had to create a new PR, my github skillz failing me.

**Comment by kilograham** [comment]
merged into develop
