### ISSUE TITLE
TREQ_SEL enumeratedValues misses many choices

### ISSUE THREAD

**Issue by jannic** [raspberrypi/pico-sdk#1062]
The enumeratedValues element for TREQ_SEL in rp2040.svd only contains the TIMER values and PERMANENT, but misses all the possible values for external DREQs.

This was fixed in https://github.com/rp-rs/rp2040-pac/pull/59 by @jounathaen. I think it would be useful to add those values in the pico-sdk SVD as well.

**Comment by matiasilva** [comment]
Fixed, and thanks @jannic for providing all the information necessary.

**Comment by kilograham** [comment]
fixed
