### ISSUE TITLE
PicoW cyw43_arch_threadsafe_background grabs wrong gpio for it's interrupt

### ISSUE THREAD

**Issue by envirocoder** [raspberrypi/pico-sdk#1068]
GPIO13 was handled by the wrong interrupt handler. Fixed in pull request.

**Comment by lurch** [comment]
#1069 has been merged, so I guess this can be closed?

**Comment by kilograham** [comment]
merged into develop

**Comment by MrGreensWorkshop** [comment]
PRs milestone(1.4.1) is different than issues milestone(1.5.0)
