### ISSUE TITLE
Add "-b <addr>" option to elf2uf2

### ISSUE THREAD

**Issue by esky-software** [raspberrypi/pico-sdk#1071]
The input file is treated as a binary blob to be packaged at the specified address.

Handy when the application expects to find data at a known location in flash.
e.g. Config data, display resources, etc.

**Comment by kilograham** [comment]
Note there is a python script to do that here `https://github.com/microsoft/uf2/`

**Comment by esky-software** [comment]
Heh, so there is: https://github.com/microsoft/uf2/blob/master/utils/uf2conv.md
Feel free to merge or close the PR as you see fit.

**Comment by kilograham** [comment]
Yeah - it is a nice idea, but feels a bit weird in a tool called `elf2uf2`... but we will add such support if we have reason to add functionality related to making UF2s in the future

**Comment by lurch** [comment]
@will-v-pi Has this been "fixed" in picotool? I guess at the very least, this issue ought to be moved over to that repo?

**Comment by will-v-pi** [comment]
Yes, it’s been added - the option is `-o`. I closed the PR but missed this issue
