### ISSUE TITLE
Add ability to build without "panic" messages

### ISSUE THREAD

**Issue by eustas** [raspberrypi/pico-sdk#1075]
Some setups does not support stdio... so panic messages become pure waste of binary size / memory.
It should be a macro or inlined proxy function.

**Comment by kilograham** [comment]
You can; 

set`PICO_PANIC_FUNCTION` either to the name of your own function which does nothing, or set it to `0` (not empty blank as specified in docs) to have it just be a breakpoint.

e.g. via cmake:

`target_compile_definitions(TARGET PRIVATE PICO_PANIC_FUNCTION=0)`
