### ISSUE TITLE
cyw43_driver only works with SM0

### ISSUE THREAD

**Issue by Lord-Lucan** [raspberrypi/pico-sdk#1077]
The cyw43_driver (see cyw43_bus_pio_spi.c) only supports SM0. It tries to play nice by allocating a free PIO and requesting a SM but if it gets an SM other than 0 it doesn't work.

The workaround is to make sure that you keep SM 0 free on a PIO for this driver.

In cyw43_bus_pio_spi.c (line 263) we have code like this ....
` dma_channel_configure(bus_data->dma_out, &out_config, &bus_data->pio->txf[0], tx, tx_length / 4, true);`
Which is hardwiring the DMA to pio SM 0 fifo.

Have tried to fix, but not completely working yet :(

**Comment by kilograham** [comment]
I would thing just changing from `txf[0]` to `txf[bus_data->pio_sm]` should do it, no? (also for the other `txf[0]/rxf[0]`)

**Comment by Lord-Lucan** [comment]
Hi, thanks for the reply. Yes tried all of that, there are other places in the code where it's hard coded as well. But it still doesn't transfer properly. So it's a bit more deep rooted. I'll take a deeper look at the weekend. At the moment I've just made sure my SM is not claiming 0.

**Comment by Lord-Lucan** [comment]
I was wondering if it might have to do with the offset in the SM memory. Because I bet it's never had to share with another program.

**Comment by Lord-Lucan** [comment]
Worked out what the final issue was, there needed to be a change to the fdebug flag for the SM in use, see PR.

**Comment by kilograham** [comment]
merged into develop
