### ISSUE TITLE
Defining a custom stage 2 bootloader

### ISSUE THREAD

**Issue by agalauner-r7** [raspberrypi/pico-sdk#1082]
Hi,
I am currently trying to define an executable and my own custom stage 2 bootloader. However, I can't make the definition of the custom bootloader work. I've been digging through the cmake code and search for other projects doing this for hours now, but I can't find the issue and I only find other projects which change preprocessor defines for one of the standard stage 2 bootloaders and they don't define their own.

This is what part of my `CMakeLists.txt` currently looks like:
```
add_executable(blinky_cust_boot blinky.c)
target_link_libraries(blinky_cust_boot pico_stdlib)
pico_add_extra_outputs(blinky_cust_boot)

pico_define_boot_stage2(boot_blinky boot_blinky.S)
pico_set_boot_stage2(blinky_cust_boot boot_blinky)
```
`boot_blinky.S` is my custom stage 2 loader that is supposed to be prepended to my `blinky_cust_boot` application that is compiled from `blinky.c`.

When I do this, cmake complains like this:
```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_ASM_LINK_EXECUTABLE
```

The build doesn't succeed properly, because it apparently doesn't know how to link `.S` files, even though it does how to do that with the default loaders?

When I call `pico_define_boot_stage2` with a `.c` instead of an `.S`-file, the build succeeds, but I need to write my stage 2 loader in assembly, obviously.

Any help on how to possibly make this work is greatly appreciated!

**Comment by kilograham** [comment]
questions like this best asked here https://forums.raspberrypi.com/viewforum.php?f=143

i think tho you haven't included "ASM" in the `project(` call in your `CMakeLists.txt`
