### ISSUE TITLE
PicoW WiFi connect APIs don't allow specifying BSSID

### ISSUE THREAD

**Issue by earlephilhower** [raspberrypi/pico-sdk#1090]
The underlying CYW43 driver supports specifying an AP to connect to using explicit SSID and BSSID (MAC) options, but the SDK API calls do not.

Using explicit BSSIDs is handy in the case of mesh networks, or where multiple APs use the same SSID (i.e. it is possible to scan the APs, find the one with best RSSI, and use that one).

In some cases we've found the CYW43 will not connect to the AP with the highest RSSI by itself when only giving the SSID.

**Comment by lurch** [comment]
See also #1086

**Comment by peterharperuk** [comment]
Lets see if we can get this in the next release

**Comment by kilograham** [comment]
merged into develop
