### ISSUE TITLE
Please, Clean SDK

### ISSUE THREAD

**Issue by Wiz-IO** [raspberrypi/pico-sdk#1103]
Each end user SDK version must be complete ( no submodule links ) and cleaned of unnecessary files
eg: effective code is 6M vs ~60M .git vs ~76M for full folder

at the very least, the download speed increases
At least i think so...

**Comment by JamesH65** [comment]
git clone --depth?

Or have I misunderstood the question?

**Comment by Wiz-IO** [comment]
yep, there are options and solutions (by default)
my thought is that there are a lot of junk files for the end user
and I thought a simple repo (end version) optimization wouldn't hurt
I look Kilogram has prepared mbedtls, which will further increase the final transfer

**Comment by Wiz-IO** [comment]
![git](https://user-images.githubusercontent.com/14574834/202674352-e59a6ca1-bad5-4383-91dc-22f97bd57040.jpg)

**Comment by aallan** [comment]
Sorry, not entirely sure what the question is?

**Comment by Wiz-IO** [comment]
no question, just an optimization tip

**Comment by peterharperuk** [comment]
Which files do you think are unnecessary?

**Comment by Wiz-IO** [comment]
for the end user, only SRC & LIB are effective, maybe DOC too
for what is the student's 60M dot git folder ( with the entire history of the repo ) 
there is always a dev repo

and source codes for ESP32, TI etc...

**Comment by Wiz-IO** [comment]
here's a question for you
for me, the PICO-SDK installation is 20 seconds( ~80 megabytes, effective 7 )
how much is it with you?
and how much is per board RPI?

**Comment by JamesH65** [comment]
I just did a git clone https://github.com/raspberrypi/pico-sdk.git and it took about 3s. (This is my home net connection, not in the office)

What do you mean by "and how much is per board RPI?"

**Comment by Wiz-IO** [comment]
3 sec, nice
Raspberry Pi 4

**Comment by JamesH65** [comment]
The SDK tree seems to be about 13MB accord to "du".

Do you mean how long it takes to download on a Pi4? About the same, 2.5s

**Comment by Wiz-IO** [comment]
ok

**Comment by peterharperuk** [comment]
Presumably you have to add the time to execute something like "git submodule update --init --depth 1"?

**Comment by JamesH65** [comment]
So the submodule stuff took 9.6s on the Pi4.

Bumped size on disk up to 41MB.

**Comment by kilograham** [comment]
note #1044 will fix the biggest offender

**Comment by lurch** [comment]
Note that if you want to download the source code for the SDK without getting the `.git` folder too, you can download one of the zip files from https://github.com/raspberrypi/pico-sdk/releases
`pico-sdk-1.4.0.zip` is only 1.2MB.

**Comment by Wiz-IO** [comment]
I needed it for automatic installation and updates - PlatformIO / Pico SDK the **full** version 
with git install/update...
other solutions become complicated
