### ISSUE TITLE
lwip-mqtt: sys_timeout: timeout != NULL, pool MEMP_SYS_TIMEOUT is empty #1 

### ISSUE THREAD

**Issue by pingufreak** [raspberrypi/pico-sdk#1106]
Hi all,

I'm using pico_cyw43_arch_lwip_threadsafe_background with the lwip mqtt library. Anyways, I'm getting:

> *** PANIC ***
> sys_timeout: timeout != NULL, pool MEMP_SYS_TIMEOUT is empty`

The implementation is based on pico-sdk/lib/lwip/contrib/examples/mqtt/mqtt_example.c :

> int main() {
>  stdio_init_all();
>  if(cyw43_arch_init_with_country(CYW43_COUNTRY_GERMANY)) {
>   printf("Failed to initialise cyw43_arch\n");
>  }
>  cyw43_arch_enable_sta_mode();
>  if(cyw43_arch_wifi_connect_timeout_ms(WIFI_SSID, WIFI_PASSWORD, CYW43_AUTH_WPA2_AES_PSK, 10000)) {
>   printf("Failed to connect to WiFi\n");
>  }
>  mqtt_example_init();
>  while(true) {
>   printf("loop\n");
>   sleep_ms(1000);
>  }
>  return 0;
> }

I've also implemented it from scratch with the documentation  `pico-sdk/lib/lwip/doc/mqtt_client.txt` with the same result.

I've also tested the implementation of https://github.com/cniles/picow-iot with the same result.

Do you have an idea? Maybe there are issues with the sys_timers of the library itself? 

Is the mqtt-library only supported with FreeRTOS or also working with pico_cyw43_arch_lwip_threadsafe_background?

Thank you!

Kr

pingufreak

**Comment by pingufreak** [comment]
I've increased LWIP_NUM_SYS_TIMEOUT_INTERNAL and it works now.

**Comment by kilograham** [comment]
assuming this can be closed?

**Comment by albertasgalin** [comment]
Thanks! [pingufreak](https://github.com/pingufreak) it realy helped!

**Comment by ruswerner** [comment]
@pingufreak What was the value you used? and what specific define did you set?

I ended up getting it working by doing this in my header:

```
#define MEMP_NUM_SYS_TIMEOUT (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 100)
```

... however I was just guessing at the value and setting it too high produces a compilation failure due to binary size too large to fit in RAM.

**Comment by ruswerner** [comment]
I think I found my answer by searching the `pico_sdk` folder...  There is a txt file in `<SDK>/lib/lwip/doc/mqtt_client.txt` with this note at the top:

```
You need to increase MEMP_NUM_SYS_TIMEOUT by one if you use MQTT!
```

I feel like this should be more explicitly addressed in the code examples!

**Comment by lurch** [comment]
Note that anything in `<SDK>/lib/lwip/` is coming from https://github.com/lwip-tcpip/lwip rather than directly from pico-sdk itself.

**Comment by OKuvshinov** [comment]
> I think I found my answer by searching the `pico_sdk` folder... There is a txt file in `<SDK>/lib/lwip/doc/mqtt_client.txt` with this note at the top:
> 
> ```
> You need to increase MEMP_NUM_SYS_TIMEOUT by one if you use MQTT!
> ```
> 
> I feel like this should be more explicitly addressed in the code examples!

I use SNTP and Wireguard. Increasing this value from 3 to 6 helps me too

**Comment by mjcross** [comment]
According to the lwIP source we should increase `MEMP_NUM_SYS_TIMEOUT` by one for (each of) **MQTT**, **MDNS**, **TFTP** and **SNTP**:
```
doc/mqtt_client.txt:You need to increase MEMP_NUM_SYS_TIMEOUT by one if you use MQTT!
src/apps/mdns/mdns.c: * You need to increase MEMP_NUM_SYS_TIMEOUT by one if you use MDNS!
src/apps/tftp/tftp.c: * You need to increase MEMP_NUM_SYS_TIMEOUT by one if you use TFTP!
src/apps/sntp/sntp.c: * You need to increase MEMP_NUM_SYS_TIMEOUT by one if you use SNTP!
```
It is also notable that all of the test configurations in `lwip/contrib/examples/example_app/test_configs` except the `no_tcp` and `no_udp` ones add an extra 2 timeouts which might be prudent...
```
opt_default.h:#define MEMP_NUM_SYS_TIMEOUT            (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 2)
opt_dualstack.h:#define MEMP_NUM_SYS_TIMEOUT            (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 2)
opt_ipv4only.h:#define MEMP_NUM_SYS_TIMEOUT            (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 2)
opt_ipv6only.h:#define MEMP_NUM_SYS_TIMEOUT            (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 2)
opt_nosys_dual.h:#define MEMP_NUM_SYS_TIMEOUT            (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 2)
opt_nosys_ipv4.h:#define MEMP_NUM_SYS_TIMEOUT            (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 2)
opt_nosys_ipv6.h:#define MEMP_NUM_SYS_TIMEOUT            (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 2)
```
