### ISSUE TITLE
Dont exclude baudrate BOOTSEL reset trick from build when LIB_TINYUSB_HOST or LIB_TINYUSB_DEVICE is defined

### ISSUE THREAD

**Issue by popy2k14** [raspberrypi/pico-sdk#1118]
As the title says and discussed here: https://github.com/raspberrypi/pico-sdk/issues/838#issuecomment-1325602575

Please do not exclude function tud_cdc_line_coding_cb() from file /rp2_common/pico_stdio_usb)/reset_interface.c
The function is very helpful to bring the pi into BOOTSEL mode when TinyUSB is used.
A better approach would be to include it always and make an define to exclude it, when not needed.

As a workaround, i have just copied, adapted and inserted the function into my project, like this

```
// Support for default BOOTSEL reset by changing baud rate
void tud_cdc_line_coding_cb(__unused uint8_t itf, cdc_line_coding_t const* p_line_coding) {
    if (p_line_coding->bit_rate == 110) {    
        //board_led_write(1);
        reset_usb_boot(gpio_mask, 0);
    }
}
```

**Comment by kilograham** [comment]
We will now respect PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1 if you set it when using TinyUSB yourself (it won't default to 1 like it does when you aren't using TinyUSB)

**Comment by kilograham** [comment]
This should work fine with SDK 2.0.0

**Comment by akohlsmith** [comment]
@kilograham I'm trying to use this (my use case is that I only *need* tusb in host mode on the secondary (PIO) USB interface, but I'm new to tinyusb so I don't know if it's one of those "if you're using tusb it's going to be used for both" situations.

Right now I'm just using the "dual CDC device" demo code: I put `set(PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE 1)` in my toplevel CMakeLists.txt, before the `pico_sdk_init()` line, and my main() calls board_init() and tusb_init() (and board_init_after_tusb()) before it calls stdio_init_all(). Building and flashing is fine, I do have two CDC devices and they work, but `picotool info` doesn't see any compatible devices that it can force into bootsel mode. I tried setting the baudrate to 1200 to see if that would trigger a reboot to bootsel but no dice.

I'm sure I'm missing something very basic and I'm going to feel dumb for not realizing it but I can't see it. What am I doing wrong? I'm using SDK 2.2.0.

**Comment by lurch** [comment]
> but `picotool info` doesn't see any compatible devices that it can force into bootsel mode

Correct, I believe that `picotool` only knows about the `PICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE` and knows nothing about the `PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE`.

> I'm sure I'm missing something very basic and I'm going to feel dumb for not realizing it but I can't see it. What am I doing wrong?

This is the sort of question that you ought to be asking on the [forums](https://forums.raspberrypi.com/viewforum.php?f=143), rather than on GitHub.
