### ISSUE TITLE
PPB: missing C API for setting the SysTick, and other exceptions priorities

### ISSUE THREAD

**Issue by DipSwitch** [raspberrypi/pico-sdk#1135]
Currently there is no C API for setting the SHRP2 and SHRP3 registers. So now I have to set the priority of the exceptions with something like this:

```
io_rw_32 *p = (io_rw_32 *)((PPB_BASE + M0PLUS_SHPR3_OFFSET));
*p |= ((0xc0) << (M0PLUS_SHPR3_PRI_15_LSB / 8 * 8));
```

**Comment by alastairpatrick** [comment]
https://github.com/raspberrypi/pico-sdk/issues/987

**Comment by kilograham** [comment]
closing as duplicate of #987
