### ISSUE TITLE
Bluetooth/BLE Support in CYW43

### ISSUE THREAD

**Issue by bizzehdee** [raspberrypi/pico-sdk#1163]
In the release for the Pico w, it was mentioned that WiFi is supported immediately and Bluetooth will be available soon after release.

It's now over 6 months since the release of the Pico w and there are no mentions of Bluetooth or BLE in this issue tracker or the CYW43 issue tracker.

It's Bluetooth going to happen on the Pico W, or is there some sort of hardware limitation preventing it from being possible?

**Comment by aallan** [comment]
It's being worked on internally, and is fairly close to release. I can't give an exact timeline, but I'd expect it to be fairly soon, certainly Q1.
