### ISSUE TITLE
Bluetooth Support for Pico W

### ISSUE THREAD

**Issue by kilograham** [raspberrypi/pico-sdk#1164]

**Comment by tannewt** [comment]
Will you be using NimBLE for the host-side?

**Comment by kilograham** [comment]
Our integration uses [BTstack](https://github.com/bluekitchen/btstack)

**Comment by arturo182** [comment]
I'm no lawyer but isn't this worrying in their license?

https://github.com/bluekitchen/btstack/blob/master/LICENSE#L20

```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

[...]

4. Any redistribution, use, or modification is done solely for
   personal benefit and not for any commercial purpose or for
   monetary gain.
```

**Comment by kilograham** [comment]
It will be licensed by us for more permissive use on RP2040

**Comment by arturo182** [comment]
Thanks for the clarification 👍

**Comment by WayneKeenan** [comment]
Looking forward to this. Thanks.

**Comment by marian-m12l** [comment]
This is great news :+1: 
Just to manage expectations, could you clarify the scope for the 1.5.0 target? BLE? Dual mode? Maybe support for some profiles? Device and Host?
Thanks!

**Comment by JamesH65** [comment]
I'm not sure we will be publishing that in advance, but I will try and find out.

**Comment by cezarfloroiu** [comment]
Any updates on when Bluetooth support will be released?

**Comment by JamesH65** [comment]
I believe this should be fairly soon.

**Comment by gnbl** [comment]
> Any updates on when Bluetooth support will be released?

4 days ago, according to the [1.5.0 milestone](https://github.com/raspberrypi/pico-sdk/milestone/14)  ;-)

**Comment by znmeb** [comment]
> > Any updates on when Bluetooth support will be released?
> 
> 4 days ago, according to the [1.5.0 milestone](https://github.com/raspberrypi/pico-sdk/milestone/14) ;-)

Time flies when your teeth are blue ;-)

**Comment by kilograham** [comment]
> > > Any updates on when Bluetooth support will be released?
> > 
> > 
> > 4 days ago, according to the [1.5.0 milestone](https://github.com/raspberrypi/pico-sdk/milestone/14) ;-)
> 
> Time flies when your teeth are blue ;-)

literally from the cold, and the power being out

**Comment by SpeedyCraftah** [comment]
Enough of the chatter lads, time to emit some radio waves 🌊 📻

**Comment by peterharperuk** [comment]
The gears are turning https://github.com/georgerobotics/cyw43-driver/pull/60

**Comment by BenRoe** [comment]
Any changes on the PCB needed, to support Bluetooth with the Pico W?
Or is it only a software thing?

**Comment by kilograham** [comment]
Beta support released into SDK 1.5.0 and `pico-examples` 

see https://github.com/raspberrypi/pico-sdk/releases/tag/1.5.0

**Comment by carlosdelfino** [comment]
Hello, is there any tutorial in C/C++ that demonstrates how to use Bluetooth with the RP Pico W? Has BTstack been released for commercial use? Thanks.

**Comment by lurch** [comment]
@carlosdelfino See https://github.com/raspberrypi/pico-examples/?tab=readme-ov-file#pico-bluetooth and https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_btstack/LICENSE.RP
