### ISSUE TITLE
Documentation of at_the_end_of_time is wrong

### ISSUE THREAD

**Issue by mthiesen** [raspberrypi/pico-sdk#1171]
The documentation of `at_the_end_of_time` states:

_The timestamp representing the end of time; this is actually not the maximum possible timestamp, but is set to 0x7fffffff_ffffffff microseconds to avoid sign overflows with time arithmetic. This is still over 7 million years, so should be sufficient._

However the number of microseconds in a year is 1,000,000 * 60 * 60 * 24 * 365 = 31,536,000,000,000. 0x7fffffffffffffff / 31,536,000,000,000 is about 292471.21. Still a very long time but certainly not 7 million years.

**Comment by kilograham** [comment]
fixed by #1186

**Comment by kilograham** [comment]
merged into develop
