### ISSUE TITLE
Calling alarm_pool_cancel_alarm() with an ID of 0 will assert

### ISSUE THREAD

**Issue by mthiesen** [raspberrypi/pico-sdk#1172]
Calling `alarm_pool_cancel_alarm(pool, 0)` or `cancel_alarm(0)` will trigger the assert `assert(alarm_id != pool->alarm_in_progress)`.

Nothing in the documentation states that calling these functions with `0` as an ID is not allowed. Instead `false` should be returned because an alarm with ID 0 does not (and cannot) exist.

**Comment by kilograham** [comment]
merged into develop
