### ISSUE TITLE
Is it possible to add WPA2 enterprise?

### ISSUE THREAD

**Issue by syedzayyan** [raspberrypi/pico-sdk#1175]
MicroPython has never added support for this, and I was hoping if it would be possible to add it here of it its already supported.

**Comment by lurch** [comment]
Is this a similar question to https://github.com/raspberrypi/documentation/issues/2722 and https://github.com/micropython/micropython/discussions/10399 ?
AIUI https://github.com/georgerobotics/cyw43-driver is where the driver-support would need to be added.

**Comment by aallan** [comment]
MicroPython specific questions are probably better directed to the MicroPython forum, https://forum.micropython.org/viewforum.php?f=21.
