### ISSUE TITLE
A question about the code comments of the watchdog module

### ISSUE THREAD

**Issue by mbiusxxx** [raspberrypi/pico-sdk#1241]
https://github.com/raspberrypi/pico-sdk/blob/2ccab115de0d42d31d6611cca19ef0cd0d2ccaa7/src/rp2_common/hardware_watchdog/include/hardware/watchdog.h#L75
Maybe there's an error in it: milliseconds -> microsecond

**Comment by lurch** [comment]
Duplicate of #1238
