### ISSUE TITLE
lwip submodule should point to a tag or branch tip in the remote repository

### ISSUE THREAD

**Issue by ali1234** [raspberrypi/pico-sdk#1244]
Currently the lwip submodule points to an arbitrary commit c385f31076b27efb8ee37f00cb5568783a58f299. Most git servers, including GNU Savannah, only allow shallow clones of branch tips and tags. This means if you do a shallow recursive clone of pico-extras (for example, in a CI pipeline), you will get the following error:

    Error: error: Server does not allow request for unadvertised object c385f31076b27efb8ee37f00cb5568783a58f299
    Error: fatal: Fetched in submodule path 'lib/lwip', but it did not contain c385f31076b27efb8ee37f00cb5568783a58f299. Direct fetching of that commit failed.

User must instead do a full clone of the submodule, which might mean doing a full clone of pico-extras too. This is slow, wastes bandwidth and electricity, uses up extra Actions minutes, and hammers the GNU servers.

This can be fixed by either changing the submodule to point to an existing tag or branch (if branch, you have to keep on updating the submodule whenever the branch tip changes), or by forking the upstream repository and adding a tag to the commit you want to use, and then adjusting the submodule to point to your fork.

**Comment by ali1234** [comment]
I am not sure why it works now. It could be because the remote now points to the github mirror instead of savannah, and github might configure their servers differently. They never used to allow this either though.

**Comment by kilograham** [comment]
um; i'm a bit confused, as this issue seems to refer repeatedly to `pico-extras` not `pico-sdk`... in any case it doesn't seem like #1369 is a suitable fix anyway, so won't fixing this for now - please re-open if there is still an issue

**Comment by ali1234** [comment]
This issue was opened when lwip was a submodule of pico-extras. It is now a submodule of pico-sdk, and you moved the issue here when lwip was moved.

**Comment by kilograham** [comment]
ha

**Comment by kilograham** [comment]
anyways, i'm not sure there is much to be done, unless lwip makes a newer tag, right?

**Comment by ali1234** [comment]
It does seem that this is no longer a problem. I am not sure why because github definitely is not advertising https://github.com/lwip-tcpip/lwip/tree/239918ccc173cb2c2a62f41a40fd893f57faf1d6 (you can confirm this with `git ls-remote`.) It seems to be a change in the behavior of the git command itself, to download the full remote even when you ask for a shallow clone - and then discard anything it doesn't need.
