### ISSUE TITLE
Move compile guard in cyw43_arch_poll.c 

### ISSUE THREAD

**Issue by esky-software** [raspberrypi/pico-sdk#1268]
The compile guard at line 10 of cyw43_arch_poll.c 
#if PICO_CYW43_ARCH_POLL
can be moved to before any #include lines.

Makes life a tiny bit easier when building an alternative to the SDK's driver architecture.

**Comment by kilograham** [comment]
always welcome PRs

**Comment by kilograham** [comment]
merged into develop
