### ISSUE TITLE
Mechanism for setting exception handlers

### ISSUE THREAD

**Issue by davidgiven** [raspberrypi/pico-sdk#127]
I could be wrong, but there doesn't appear to be any way of setting exception handlers from code other than to create specially-named functions such as `isr_svcall`, which the documentation suggestsnot to do.

The implementation numbers interrupts/exceptions from 0 for IRQ0. As these appear immediately after the vector table, it ought to be possible to use negative numbers to refer to the exceptions --- these are actually documented in the ARM documentation at https://developer.arm.com/documentation/dui0497/a/the-cortex-m0-processor/exception-model/exception-types, so `SVCall` is interrupt -5. However, calling `irq_set_exclusive_handler()` doesn't work because you can only use it on vectors which are already pointing at `__unhandled_user_irq`.

Given how clean the rest of the SDK's design is, it'd be nice to have a blessed-by-the-API way of doing this.

**Comment by kilograham** [comment]
that is really good point! you can certainly use isr_svcall as a workaround for now, but we should add an API

**Comment by kilograham** [comment]
note also that the vector table is installed in RAM by default, also, so you could write to this... 

Also note, that we are working on FreeRTOS "port"

**Comment by kilograham** [comment]
merged into develop
