### ISSUE TITLE
Help implementing CY43 gSPI

### ISSUE THREAD

**Issue by soypat** [raspberrypi/pico-sdk#1270]
Hello Rpi peeps,
I'm currently developing with TinyGo and wanted to implement CY43439 support to make use of the on board wifi capabilities. 

I've gotten [thus far](https://github.com/soypat/cyw43439), been able to read/write via an SPI bitbang implementation. The data I'm getting back from the chip is nonsense for the time being and it's very hard to debug without being able to hook up a logic analyzer to the CY's DIN/DOUT or GPIO24. So I was wondering if you guys had any SPI transaction samples used for the development of the pico-sdk's implementation. Anything helps really, images, tips and whatnot!

**Comment by soypat** [comment]
Also wondering if there's firmware installed on the CY beforehand or if I'd need to flash it first...

**Comment by lurch** [comment]
I guess you probably ought to be asking these questions at https://github.com/georgerobotics/cyw43-driver ?

**Comment by soypat** [comment]
Update:
So I've managed getting the IO working on SPI! I have not been able to set the GPIO pins because the F1RxReady status check is failing. This is because I need to download the firmware to the CY43, no?

**Comment by kilograham** [comment]
closing this, as this isn't an SDK issue
