### ISSUE TITLE
Increasing the maximum timeout for Watchdog

### ISSUE THREAD

**Issue by diwakrZha** [raspberrypi/pico-sdk#1277]
For my battery operated application, RPI PICO-W should wake up only every 20 minutes or longer. With maximum timeout for Watchdog timer, 8388 ms, I have to keep feeding much often than necessary? 

Is there a way to increase the maximum timeout of the Watchdog? or another way to mitigate possible hangs?

Thanks,

**Comment by liamfraser** [comment]
This isn't really the intended use of the watchdog. I would recommend setting an alarm on the normal timer which is 32 bits. See https://github.com/raspberrypi/pico-examples/blob/master/timer/hello_timer/hello_timer.c for usage. You can then go into `__wfi();` and wait for the timer interrupt to go off.

**Comment by bruelltuete** [comment]
the watchdog is clocked by clk_ref. You could change clk_ref to something slower, e.g. rosc (or maybe there's some clock division tricks you could do).

**Comment by kilograham** [comment]
closing this as there isn't an intention to "fix" anything
