### ISSUE TITLE
Wstrict-prototypes

### ISSUE THREAD

**Issue by Wiz-IO** [raspberrypi/pico-sdk#128]
Hi,

please correct **void** prototypes in header files...

as example:
src\common\pico_stdlib\include/pico/stdlib.h:74:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]

**Comment by kilograham** [comment]
already done in develop

**Comment by lurch** [comment]
(fixed by #95 )

**Comment by Wiz-IO** [comment]
[hardware/sync.h](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_sync/include/hardware/sync.h#L208):208:54: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

**Comment by lurch** [comment]
@Wiz-IO It's probably best to report problems with `-Wsign-compare` in a new issue, rather than adding them to a **closed** issue about `-Wstrict-prototypes` :wink:
