### ISSUE TITLE
More tight_loop_contents() ?

### ISSUE THREAD

**Issue by lurch** [raspberrypi/pico-sdk#1290]
This _may_ be a stupid question, which is why I'm asking in an issue rather than just creating a PR :wink: 

Should there be a `tight_loop_contents()` on any / all of these lines?
https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_sync/include/hardware/sync.h#L257
https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_xosc/xosc.c#L38
https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_xosc/xosc.c#L47
https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_xosc/xosc.c#L54

**Comment by kilograham** [comment]
yes!

**Comment by kilograham** [comment]
merged into develop
