### ISSUE TITLE
How to use TLS with certificate check

### ISSUE THREAD

**Issue by busslina** [raspberrypi/pico-sdk#1299]
Instead of using `tlsConfig = altcp_tls_create_config_client(NULL, 0);`. I tried "thousand" ways and no positive result.

With NULL and zero values it works great, but I think it is not a proper way to connect our pico to our server.

https://github.com/raspberrypi/pico-examples/issues/337

**Comment by peterharperuk** [comment]
You need to pass the certificate into that function and set ALTCP_MBEDTLS_AUTHMODE=MBEDTLS_SSL_VERIFY_REQUIRED
I will close this and add an example as part of https://github.com/raspberrypi/pico-examples/issues/337
