### ISSUE TITLE
SYSV vs GNU/Linux

### ISSUE THREAD

**Issue by andrei-edward-popa** [raspberrypi/pico-sdk#1308]
Hi,
In my latest project I tried to use tflite micro to compile the person detection example for pico, but a strange thing happens. Normally, using file command, the executable has the following format: 
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, with debug_info, not stripped
But for some executables the format is the following:
ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, with debug_info, not stripped
The problem is that the ABI is changed and in the case of GNU/Linux ABI the elf2uf2 cannot work because it requires the ABI to be 0 (SYSV). The code is compiled in the same manner, nothing changed. I used arm-none-eabi-g++ version 10.2. Do you have some hints about this?

**Comment by peterharperuk** [comment]
I think you would have more luck asking questions in the forum https://forums.raspberrypi.com/viewforum.php?f=144
