### ISSUE TITLE
pico/cyw43_arch.h missing cyw43_arch_disable_ap_mode()

### ISSUE THREAD

**Issue by michaelbusby** [raspberrypi/pico-sdk#1329]
after initializing cyw43_arch_init(), I enable the access point and then try and connect the sta. If the sta is successful I want to disable the access point. 

I am trying to build a "captive portal" for initial setup and configurations utilizing a pico_w board. 

This issue will link to a pull request adding a new function within cyw43_arch.h cyw43_arch_disable_ap_mode() to simple turn off the AP mode.

**Comment by michaelbusby** [comment]
see pull request #1330

**Comment by kilograham** [comment]
merged into develop
