### ISSUE TITLE
Docs for time.localtime()

### ISSUE THREAD

**Issue by hasenradball** [raspberrypi/pico-sdk#1332]
Hi Together,

I would remark that this description in the Doc is a little bit missleading.

'''
time.mktime()
[https://docs.micropython.org/en/latest/library/time.html ](https://docs.micropython.org/en/latest/library/time.html#time.mktime)
This is inverse function of localtime. It’s argument is a full 8-tuple which expresses a time as per localtime. It returns an integer which is the number of seconds since Jan 1, 2000.
''''

Because on the Pico W the RTC works with the epoch since 1970.
Maybe a small redesign of this description would be perfect, my opinion.

A other point is that I want to aks what the actual status is about:
time.gmtime()
time.localtime()

Is there actually a Timezone information available in micropython?
If not Iam right that these two functions leads to the same result in time structure?

Thanks
Frank

**Comment by kilograham** [comment]
Micropython issues belong here https://github.com/micropython/micropython

**Comment by hasenradball** [comment]
@kilograham 

Should I write the issue again?
Or what is the point behind?
Or will you move the topic?

**Comment by hasenradball** [comment]
Sorry I seems something was going wrong.
I would thing I wrote it in the micropython part.
