### ISSUE TITLE
btstack_config.h: No such file or directory

### ISSUE THREAD

**Issue by SpeedyCraftah** [raspberrypi/pico-sdk#1336]
For some reason after building RPI with the board specified as Pico W, after attempting to compile I am getting this missing header error: `btstack_config.h: No such file or directory`

Any ideas?

Full trace: https://hastebin.com/share/edeqizesur.bash
Ubuntu 20

**Comment by kilograham** [comment]
Please ask questions here https://forums.raspberrypi.com/viewforum.php?f=145

Also probably include your cmake configuration output
