### ISSUE TITLE
Arbitrary string length hard coded in tud_descriptor_string_cb() in stdio_usb_descriptors.c

### ISSUE THREAD

**Issue by hubiscode** [raspberrypi/pico-sdk#1339]
The length of USB descriptor strings is limited to 20 characters through a define statement in the descriptor call back:

```
const uint16_t *tud_descriptor_string_cb(uint8_t index, __unused uint16_t langid) {
    #define DESC_STR_MAX (20)
    static uint16_t desc_str[DESC_STR_MAX];
```

Since version 1.5, it is possible to supply custom manufacturer and product strings by defining USBD_MANUFACTURER and USBD_PRODUCT, but they get truncated at 20 characters.  It would be nice to permit a user-defined maximum string length, e.g.,  by defining USBD_DESC_STR_MAX and changing the call back code to

```
const uint16_t *tud_descriptor_string_cb(uint8_t index, __unused uint16_t langid) {
#ifndef USBD_DESC_STR_MAX
#define USBD_DESC_STR_MAX (20)
#elif USBD_DESC_STR_MAX > 127
#error USBD_DESC_STR_MAX too high (max is 127).
#elif USBD_DESC_STR_MAX < 16
#error USBD_DESC_STR_MAX too low (min is 16).
#endif
    static uint16_t desc_str[USBD_DESC_STR_MAX];
```

The preprocessor statements above include range checking for the maximum descriptor length so it is always long enough to return the serial number and not longer than the maximum possible length.

**Comment by hubiscode** [comment]
I created a pull request and fixed the bounds check. The lower bound is 17 (16 for the serial number plus 1 header).

**Comment by kilograham** [comment]
merged into develop
