### ISSUE TITLE
Distribute pioasm as a package/executable

### ISSUE THREAD

**Issue by yonsch** [raspberrypi/pico-sdk#1345]
It would be very convenient to have `pioasm` distributed as a package, in addition to the current state where it's distributed as source code that should be compiled as part of the project. This was mentioned in #396 but that issue seemed to drift to other areas.
By "package" I mean a standalone application that can be installed with the user's package manager, e.g. `apt install pioasm`.
Other options are a downloadable executable, or even a python wrap that could be installed with `pip install pioasm`.

Context: I'm porting the PIO to Zephyr, which does not use `pico-sdk`'s build system. We would prefer to have pioasm installed once as part of the installation process, rather than building it as part of the main build.

**Comment by will-v-pi** [comment]
We now have downloadable executables for pioasm (the zip is named pico-sdk-tools) and picotool available from the [pico-sdk-tools repository](https://github.com/raspberrypi/pico-sdk-tools/releases). Currently these are built for Windows x64, MacOS x64 and arm64, and Linux x64 (Ubuntu) and arm64 (Raspberry Pi OS).

These include cmake config files, so if you're using CMake to find the packages then you can simply download and unzip the file, then add
```
set(pioasm_DIR /path/to/pioasm)
find_package(pioasm 2.0.0 QUIET CONFIG NO_CMAKE_FIND_ROOT_PATH)
```
to your CMakeLists.txt.

See the `pico_init_pioasm` and `pico_init_picotool` functions in tools/CMakeLists.txt for how the SDK does this
