### ISSUE TITLE
Pico W spi state machine

### ISSUE THREAD

**Issue by thrandale** [raspberrypi/pico-sdk#1351]
The pico_cyw43_driver uses a state machine for the `spi_gap01_sample0` program within `cyw43_spi_init()` in `src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c`

Is this necisary?

I am working on a project where I am utilizing enough state machines / program memory that the `cyw43_arch_init()` is failing because the it cannot claim one.

The only functionality of the wireless chip I require is Bluetooth Low Energy. Does this require that the cyw43_spi_init claims a state machine?

Regardless, There should be a better error when this happens. It just says "Failed to open cyw43 hci controller: -6". It took much tracing through source code to find the root of the issue.
Should also maybe add documentation somewhere noting that a state machine is used by the cyw43 library.

**Comment by peterharperuk** [comment]
Yes, it's necessary if you want to use Bluetooth.
