### ISSUE TITLE
 It seems that the RX fifo is cleaned twice.

### ISSUE THREAD

**Issue by rspber** [raspberrypi/pico-sdk#1359]
/*! \brief Clear a state machine's TX and RX FIFOs
 *  \ingroup hardware_pio
 *
 * \param pio The PIO instance; either \ref pio0 or \ref pio1
 * \param sm State machine index (0..3)
 */
static inline void pio_sm_clear_fifos(PIO pio, uint sm) {
    // changing the FIFO join state clears the fifo
    check_pio_param(pio);
    check_sm_param(sm);
    hw_xor_bits(&pio->sm[sm].shiftctrl, PIO_SM0_SHIFTCTRL_FJOIN_RX_BITS);
    hw_xor_bits(&pio->sm[sm].shiftctrl, PIO_SM0_SHIFTCTRL_FJOIN_RX_BITS);
}

**Comment by kilograham** [comment]
it flips the RX bit twice (so it ends up where it started, with the side effect of clearing the FIFOs)
