### ISSUE TITLE
pico_malloc.c doesn't include pico/malloc.h

### ISSUE THREAD

**Issue by geurtv** [raspberrypi/pico-sdk#136]
pico_malloc.c doesn't include pico/malloc.h (directly or indirectly). This means PICO_USE_MALLOC_MUTEX will always be 0 even with pico_multicore and PICO_MALLOC_PANIC now defaults to 0 instead of 1.

**Comment by geurtv** [comment]
Additionally in pico_malloc.c, when pico/malloc.h is included PICO_DEBUG_MALLOC is always on because

> `#ifdef PICO_DEBUG_MALLOC`

is used instead of 

> `#if PICO_DEBUG_MALLOC`

**Comment by kilograham** [comment]
Spooky; i just noticed this last night!

**Comment by kilograham** [comment]
merged to develop
