### ISSUE TITLE
Feature: `pioasm` should support machine-readable output (JSON)

### ISSUE THREAD

**Issue by byteit101** [raspberrypi/pico-sdk#1393]
Several times I've been working with external tooling, such as the great [PIO debugger](https://github.com/soundpaint/rp2040pio/) and wanted to be able to pull information out of the PIO assembly files, like side set and loop targets. A machine-readable output, like JSON, would assist in better integration & developement of external tooling for PIO ASM code.

**Comment by kilograham** [comment]
merged into develop
