### ISSUE TITLE
【rp2_common】【pico_malloc.c】Modify the code to check if rc is a null pointer before calling rc

### ISSUE THREAD

**Issue by jming912** [raspberrypi/pico-sdk#1397]
The code on lines 41, 58, and 75 of this code may attempt to convert a null pointer to a uint8_t* type and attempt to perform an addition operation on top of that pointer. This behavior is undefined, and the undefined result depends on the specific compiler and runtime environment. In some cases, this may cause the program to crash.

**Comment by jming912** [comment]
for example：
 if (!rc || ((uint8_t *)rc) + size > (uint8_t*)PICO_DEBUG_MALLOC_LOW_WATER) {
        printf("malloc %d %p->%p\n", (uint) size, rc, ((uint8_t *) rc) + size);

**Comment by kilograham** [comment]
Is this fixing an actual compiler warning? This is also in a debug path only.

**Comment by peterharperuk** [comment]
Fixed I think
