### ISSUE TITLE
Unsafe implemention of hal_flash_bank_t in pico_btstack 

### ISSUE THREAD

**Issue by geurtv** [raspberrypi/pico-sdk#1406]
As far as I can tell the current implementation of hal_flash_bank_t in pico_btstack is unsafe if both rp2040 cores are enabled, because the other core isn't locked-out during flash erase and program, correct? See Detailed Description at [hardware_flash](https://www.raspberrypi.com/documentation/pico-sdk/hardware.html#hardware_flash).

**Comment by kilograham** [comment]
#1412 merged into develop
