### ISSUE TITLE
watchdog_reboot() has misleading parameter name delay_ms, should be delay_us as the units are microseconds not milliseconds

### ISSUE THREAD

**Issue by smcameron** [raspberrypi/pico-sdk#1409]
https://github.com/raspberrypi/pico-sdk/blob/f396d05f8252d4670d4ea05c8b7ac938ef0cd381/src/rp2_common/hardware_watchdog/include/hardware/watchdog.h#L45

ms or msec is the abbreviation for milliseconds.  However, the delay_ms parameter is actually in microseconds.  The abbreviation for microseconds uses the greek letter Mu, however, it is commonly written as "us" in C-code.  The "delay_ms" parameter to watchdog_reboot should be named "delay_us", or "delay_microsecs"

**Comment by lurch** [comment]
Very similar to #1238 and #1241 ?

**Comment by smcameron** [comment]
Fair enough.
