### ISSUE TITLE
WHD_BUS_SPI_BACKPLANE_READ_PADD_SIZE error in cyw43_bus_pio_spi.c

### ISSUE THREAD

**Issue by shabaz123** [raspberrypi/pico-sdk#1410]
Hello, 

I don't know if this is an issue that may be due to just doing a git pull and git submodule update (I had an older version of the Pico SDK before), but I encountered a weird error when trying to build code for Pico W (I have not used the Pico W before).
The error was related to **WHD_BUS_SPI_BACKPLANE_READ_PADD_SIZE** not being recognized. I don't know which file that definition is declared in.

To get the code to compile, I had to hack in the following into the **cyw43_bus_pio_spi.c** file:
`#define WHD_BUS_SPI_BACKPLANE_READ_PADD_SIZE        (4)`

Now the code successfully builds and I get my binary file. I have not tried running it yet.

My question is, was that a real bug, or has my update of the Pico SDK gone wrong somewhere?
Many thanks.

**Comment by kilograham** [comment]
i think your submodules are out of sync - i just hit the same error when i was moving back and forth between new/old SDK versions (and i fixed it by updating submodules correctly)
