### ISSUE TITLE
WiFi auth_mode returned by scan is completely diffrent from defines and what connect accepts

### ISSUE THREAD

**Issue by MrJake222** [raspberrypi/pico-sdk#1413]
Related to [cyw43-driver/issues/3](https://github.com/georgerobotics/cyw43-driver/issues/3). This field seems to be a bitfield. Why it is not documented? (see [here](https://github.com/georgerobotics/cyw43-driver/blob/cd4075fc7d8c835431f5bed0e332f5a193990797/src/cyw43_ll.c#L607-L618))

**Comment by MrJake222** [comment]
The code is what it is. The pico-sdk documentation lacks

**Comment by peterharperuk** [comment]
Not an sdk issue
