### ISSUE TITLE
Boot2_is25lp080 in SDK 1.5.1 pads to all 0s

### ISSUE THREAD

**Issue by earlephilhower** [raspberrypi/pico-sdk#1429]
When the BOOT2.S files were updated in 1.5.1, the section name in the IS25LP080 code was set to `text` and not `.text`.

The missing `.` causes the actual boot code to be thrown out since the rest of the infrastructure expects `.section .text` and not `.section text`

The end result is that when you attempt to build and pad this bootloader, you end up with all 0s instead of the QSPI setup code.

**Comment by kilograham** [comment]
merged into develop
