### ISSUE TITLE
Using LwIP with TityUSB

### ISSUE THREAD

**Issue by taraskornuta** [raspberrypi/pico-sdk#1439]
Hi. I need some advice and maybe an explanation. 
I try to use LwIP stack from Pico-SDK together with TinyUSB which is also part of Pico-SDK. 
The goal is to implement a web-server and Web-UI for my device, similar as it was done[ here ](https://github.com/maxnet/pico-webserver) 
Accept I don't want to include LwIP and TinyUSB as submodules in my project. 
I also use FreeRTOS SMP and seems that I need to perform some additional integration of LwIP to respect multithreading and RTOS stuff...
I saw that LwIP stack in Pico-SDK already has all required FreeRTOS implementations. 
The question is is it possible to use "pico_cyw43_arch_lwip_sys_freertos" with USB not with cyw43 and how to do it properly?
I also have a custom board without cyw43 chip and PICO_BOARD not "pico_w"

**Comment by aallan** [comment]
This sounds like a question that would be better answered in the [C SDK section](https://forums.raspberrypi.com/viewforum.php?f=145) of the forums.
