### ISSUE TITLE
pio_sm_get doesn't return expected value

### ISSUE THREAD

**Issue by GitJer** [raspberrypi/pico-sdk#144]
I use a PIO program to insert values into the RX FIFO and read the inserted values from C/C++ using `pio_sm_get`. According to the description of the C/C++ SDK this function should:
`Read a word of data from a state machine’s RX FIFO. If the FIFO is empty, the return value is zero.` What I observe, however, is that it returns the last read value before the FIFO went empty. Below is the printf output of my C/C++ program. At the start the PIO program inserts 4 times the value 2. The number of items in the RX_FIFO (obtained via 'pio_sm_get_rx_fifo_level') correctly shows this. After 4 times reading the FIFO, 'pio_sm_get' it keeps on returning the last read value instead of 0. 

> RX_FIFO level = 4
> read value = 2
> RX_FIFO level = 3
> read value = 2
> RX_FIFO level = 2
> read value = 2
> RX_FIFO level = 1
> read value = 2
> RX_FIFO level = 0
> read value = 2
> RX_FIFO level = 0
> read value = 2

Am I correct in thinking that 'pio_sm_get' doesn't function as expected? Am I doing something wrong? How can I empty the RX_FIFO from C/C++?

**Comment by kilograham** [comment]
The value is undefined when you read from an empty FIFO (the documentation - currently still in the develop branch) was recently updated to say this.

Use `pio_sm_is_rx_fifo_empty` to guard a loop pulling data, or you can call `pio_sm_clear_fifos` to clear both TX and RX FIFO
