### ISSUE TITLE
C++ Overriding New and Delete

### ISSUE THREAD

**Issue by jondurrant** [raspberrypi/pico-sdk#1440]
New and Delete can only be overridden when C++ Exceptions are enabled with set(PICO_CXX_ENABLE_EXCEPTIONS 1).  Yet there are times when  I may wish to override New and Delete operators without using Exceptions.

My context issuing FreeRTOS Heap model for New and Delete.

**Comment by geurtv** [comment]
There's PICO_CXX_DISABLE_ALLOCATION_OVERRIDES since I guess pico-sdk 1.5.0, so with `add_compile_definitions(PICO_CXX_DISABLE_ALLOCATION_OVERRIDES=1)` pico-sdk won't override operators new and delete anymore.

**Comment by jondurrant** [comment]
Thank you.  Missed that one.

Jon

**Comment by kilograham** [comment]
There is a solution here, but i'm keeping this around to remind me as I look at cleaning up the interface with the C/C++ library

**Comment by kilograham** [comment]
i think the solution is fine for now, so closing
