### ISSUE TITLE
Please allow custom .gatt #import paths in pico_btstack_make_gatt_header()

### ISSUE THREAD

**Issue by rppicomidi** [raspberrypi/pico-sdk#1442]
I am trying to develop a custom Bluetooth LE GATT service for the Pico W that can be imported into another `.gatt` file using `#import <my_custom.gatt>`. I don't want to try to add this service to the BlueKitchen Bluetooth stack's existing default paths for `.gatt` files.

The file `${PICO_SDK_PATH}/src/rp2_common/pico_btstack/CMakeLists.txt` contains the function `pico_btstack_make_gatt_header()` that is usually invoked like this:
```
pico_btstack_make_gatt_header(my_executable PRIVATE "${CMAKE_CURRENT_LIST_DIR}/my_gap_device.gatt")
```
This causes the Python script `${PICO_SDK_PATH}/lib/btstack/tool/compile_gatt.py` to be invoked with a path to the `.gatt` file and the path to the header file. I need to the ability to add `-I${MY_CUSTOM_GATT_FILE_PATH}` to the end of the argument list so the tool can find my custom `.gatt` file when it reaches the `#import` line that calls for it. That is, I want my project's CMakeLists.txt to be able to call
```
pico_btstack_make_gatt_header(my_executable PRIVATE "${CMAKE_CURRENT_LIST_DIR}/my_gap_device.gatt" -I${MY_CUSTOM_GATT_FILE_PATH})
```

I have a simple fix for this on my local machine and I would like to submit it as a pull request. Should I submit my change as a fork from `master` or `develop` branch?

**Comment by peterharperuk** [comment]
PR's against develop please

**Comment by rppicomidi** [comment]
Submitted #1445

**Comment by kilograham** [comment]
merged into devleop
