### ISSUE TITLE
Documentation for gpio_add_raw_irq_handler functions

### ISSUE THREAD

**Issue by hubiscode** [raspberrypi/pico-sdk#1443]
The documentation for the gpio_add_raw_irq_handler*() functions does not mention that there is a limitation on the number of handlers that can be added. The limitation is due to the call to irq_add_shared_handler(), which has a limit that can be configured via PICO_MAX_SHARED_IRQ_HANDLERS. The default value in the SDK is a maximum of four handlers, of which two or three may be used by USB and the cyw43 driver. I think it would be helpful to mention the limitation since anybody installing more than one or two handlers is likely to exceed the default limit.

**Comment by MichaelBell** [comment]
Oh, I didn't realise the raw handler functions were using shared handler underneath.  That would probably explain why I'm hitting a problem, as it is extremely easy to run out of shared handlers!

**Comment by kilograham** [comment]
merged into develop
