### ISSUE TITLE
Missing `const` qualifier in `rtc_set_datetime()` & `rtc_set_alarm()`

### ISSUE THREAD

**Issue by stefanb2** [raspberrypi/pico-sdk#1454]
When you check the implementation of both APIs you can see that they only read from the passed-in `datetime_t *t`.

Hence the APIs should accept read-only instances, i.e.

* https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2_common/hardware_rtc/include/hardware/rtc.h#L57
* https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2_common/hardware_rtc/include/hardware/rtc.h#L79

should be

~~~c
bool rtc_set_datetime(const datetime_t *t);
void rtc_set_alarm(const datetime_t *t, rtc_callback_t user_callback);
~~~

This should not break any existing  code.

**Comment by kilograham** [comment]
merged into develop
