### ISSUE TITLE
Clearing destination bits automatically during DMA transfer

### ISSUE THREAD

**Issue by mryndzionek** [raspberrypi/pico-sdk#1456]
It seems that with transfer size `DMA_SIZE_8` the source address advances by one byte, but the value written to destination (PIO SM FIFO in my case) is the whole word (4-bytes). Is there a way to clear the three MSB automatically during DMA transfer? In some places on the internet I found info that this might be possible with some 'special function registers' that don't seem to be documented yet.

**Comment by kilograham** [comment]
All the registers are documented. Generally the byte lane replication when using `DMA_SIZE_8` to a PIO is not a problem (though using `DMA_SIZE_8` is potentially less efficient)... 

that said, this is a better question for the forums: https://forums.raspberrypi.com/viewforum.php?f=143
