### ISSUE TITLE
Invalid table in documentation for `gpio_set_irq_enabled`

### ISSUE THREAD

**Issue by mudge** [raspberrypi/pico-sdk#1469]
In https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2_common/hardware_gpio/include/hardware/gpio.h#L373, the table of `gpio_irq_level` values seems to be missing a column separator which causes it not to be rendered as a table, e.g. on https://www.raspberrypi.com/documentation/pico-sdk/hardware.html#rpip536c200e4b39640e0bd5

Presumably this should be the following (note the extra `|`):

```
 * bit | constant            | interrupt
 * ----|---------------------|------------------------------------
 *   0 | GPIO_IRQ_LEVEL_LOW  | Continuously while level is low
 *   1 | GPIO_IRQ_LEVEL_HIGH | Continuously while level is high
 *   2 | GPIO_IRQ_EDGE_FALL  | On each transition from high to low
 *   3 | GPIO_IRQ_EDGE_RISE  | On each transition from low to high
```

**Comment by kilograham** [comment]
merged into develop
