### ISSUE TITLE
[Documentation] Missleading documentation for uart_write_blocking()

### ISSUE THREAD

**Issue by DanielBender226** [raspberrypi/pico-sdk#1481]
The doc says that "This function will block until all the data has been sent to the UART", but it´s only blocking until all data has been sent to the tx buffer.
I think this documentation should be clarified that this function is only blocking until the data is sent to the buffer and not until the data is actually sent out.

**Comment by lurch** [comment]
See also the discussion in #1274

**Comment by lurch** [comment]
Fixed by #1772
