### ISSUE TITLE
Some modules do not work with cpp files

### ISSUE THREAD

**Issue by mbober1** [raspberrypi/pico-sdk#149]
There are some modules that don't work when the main project file has the cpp extension. 

```
#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/rtc.h"

int main()
{
    stdio_init_all();
    rtc_init();
    return 0;
}
```

When the file is called main.c everything is fine. Unfortunately, when it's called main.cpp, the project doesn't compile. 
`undefined reference to rtc_init()`

After commenting on rtc_init() everything works fine. Most of your modules work with cpp files, but there are some exceptions and the RTC module is one of them.

**Comment by kilograham** [comment]
this is already fixed in the develop branch and will be in the next release
