### ISSUE TITLE
Not possible to change CYW43 PIO settings in makefile

### ISSUE THREAD

**Issue by mvds00** [raspberrypi/pico-sdk#1498]
In its current form there is no (obvious) way to have a project with the pico-sdk as a dependency, where the project would be able to define things like the SPI_PROGRAM_NAME or the CLOCK_DIV - things that are essential to e.g. have a project that is power efficient.

It would be nice if it would be possible to define these things in a makefile. The fix is trivial and a pull request will follow, but the instructions said that an issue should be logged first.

**Comment by lurch** [comment]
Related to #1392 ?
