### ISSUE TITLE
copying `pico_sdk_import.cmake` vs referring to it directly.

### ISSUE THREAD

**Issue by devsnek** [raspberrypi/pico-sdk#15]
The official docs recommend copying `external/pico_sdk_import.cmake` into your project. I found that since `PICO_SDK_PATH` has to be set anyway, this works as well, and keeps it a bit DRYer.

```cmake
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
```

If there aren't any downsides to this (and there very well may be, I'm not that experienced with cmake), it might be worth mentioning in the docs.

**Comment by kilograham** [comment]
The reason for copying it is that it complains nicely if PICO_SDK_PATH is _not_ set! It also allows for a few other ways of initializing the SDK.

**Comment by devsnek** [comment]
Fair enough. I'll close this out.
