### ISSUE TITLE
Fail to compile: `tu_u32_low16` isn't defined when CFG_TUSB_DEBUG=3

### ISSUE THREAD

**Issue by byteit101** [raspberrypi/pico-sdk#1522]
Setting CFG_TUSB_DEBUG=3 seems to be pretty hard, I can't seem do it via cmake where CFG_TUSB_DEBUG=0 is typically defined as a command line argument. 

However, when I put `#define CFG_TUSB_DEBUG 3` in tusb_config.h, then I get build several build errors in the rp2040-specific parts of tinyusb. All the build errors are about a missing function: `tu_u32_low16` and it doesn't seem to be defined anywhere

**Comment by liamfraser** [comment]
This appears to be fixed in the latest TinyUSB master which we will move to in a future SDK release.

**Comment by kilograham** [comment]
fixed
