### ISSUE TITLE
i2c_slave.c, use incorrect define while configuring IC_INTR_MASK register in i2c_slave_init()

### ISSUE THREAD

**Issue by igor-marinescu** [raspberrypi/pico-sdk#1536]
Hello,

In file:
src\rp2_common\pico_i2c_slave\i2c_slave.c
Function: i2c_slave_init(), line 71;

`    
            I2C_IC_INTR_MASK_M_RX_FULL_BITS | I2C_IC_INTR_MASK_M_RD_REQ_BITS | I2C_IC_RAW_INTR_STAT_TX_ABRT_BITS |
`

While configuring the IC_INTR_MASK register the use of I2C_IC_RAW_INTR_STAT_TX_ABRT_BITS is wrong.
Instead I2C_IC_INTR_MASK_M_TX_ABRT_BITS must be used.

Thank you

**Comment by will-v-pi** [comment]
Linking this to #1613 which fixes this issue

**Comment by kilograham** [comment]
merged into develop
