### ISSUE TITLE
Provide pre-compiled versions of elf2uf2 and pioasm for Windows.

### ISSUE THREAD

**Issue by BrianG61UK** [raspberrypi/pico-sdk#1556]
Why do you make your Windows users grapple with the monstrosity that is Visual Studio?
What's wrong with providing precompiled versions of elf2uf2 and pioasm?
Is it that we wouldn't be suffering enough if you did that?

**Comment by lurch** [comment]
Hopefully you've already found https://github.com/raspberrypi/pico-setup-windows , which might be what you're looking for?
