### ISSUE TITLE
Not able to flash the PicoW board using Raspberry pi debug probe.

### ISSUE THREAD

**Issue by Shikamru** [raspberrypi/pico-sdk#1558]
Hi team,
            I am using raspberry pi debug probe to flash the binary to my picoW board. I am facing challenges here , i double checked the connection and installation of openocd also. openocd is up and running after entering the flash command it is showing error **"Checksum mismatch"**. 
Here is the logs -
` PS C:\Users\Documents\Pico-v1.5.1\pico-examples\build\pico_w\wifi\blink> openocd.exe -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program picow_blink.elf verify reset exit"
Open On-Chip Debugger 0.11.0-g8e3c38f78 (2023-02-28-14:54)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
Info : Hardware thread awareness created
Info : Hardware thread awareness created
Info : RP2040 Flash Bank Command
adapter speed: 5000 kHz

Info : Using CMSIS-DAPv2 interface with VID:PID=0x2e8a:0x000c, serial=E6616407E3570E29
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 2.0.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 0 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 5000 kHz
Info : SWD DPIDR 0x0bc12477
Info : SWD DLPIDR 0x00000001
Info : SWD DPIDR 0x0bc12477
Info : SWD DLPIDR 0x10000001
Info : rp2040.core0: hardware has 4 breakpoints, 2 watchpoints
Info : rp2040.core1: hardware has 4 breakpoints, 2 watchpoints
Info : starting gdb server for rp2040.core0 on 3333
Info : Listening on port 3333 for gdb connections
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
** Programming Started **
Warn : no flash bank found for address 0x10000000
Warn : no flash bank found for address 0x10041588
** Programming Finished **
** Verify Started **
target halted due to debug-request, current mode: Thread
xPSR: 0x61000000 pc: 0x1000132c msp: 0x20041fb0
Error: checksum mismatch - attempting binary compare
** Verify Failed **
shutdown command invoked`

Note -> I am working on windows environment and referring the below link for setup and flash commands.
https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html

**Comment by lurch** [comment]
Duplicate of https://github.com/raspberrypi/picoprobe/issues/110
(please don't spam the same problem to multiple repos)

**Comment by Shikamru** [comment]
> Duplicate of [raspberrypi/picoprobe#110](https://github.com/raspberrypi/picoprobe/issues/110) (please don't spam the same problem to multiple repos)

Sorry my bad ! I will close this one.
