### ISSUE TITLE
cyw43_wifi_scan returns a lot of duplicates

### ISSUE THREAD

**Issue by MrJake222** [raspberrypi/pico-sdk#1559]
As title states, running a scan with `cyw43_wifi_scan` results in same Wi-Fi with one access point be listed like 5 or 6 times.

**Comment by kilograham** [comment]
@peterharperuk is there a SDK level API for this anyway, if not can you close

**Comment by peterharperuk** [comment]
Not an sdk issue. Driver is over here https://github.com/georgerobotics/cyw43-driver
