### ISSUE TITLE
boot2_generic_06b.S

### ISSUE THREAD

**Issue by myklemykle** [raspberrypi/pico-sdk#1560]
Hi,

I have a boot2 driver that supports the Winbond W25Q128JW, and potentially other flash chips that do not support Continuous Read mode but do support Quad Fast Read (6B) commands.  This gives a major performance boost over the generic read command (3H) implemented in boot2_generic_03h, which is the only driver in the distro that doesn't require Continuous Read.

Can I submit a PR?

Thanks,
-mykle-

**Comment by kilograham** [comment]
sure

**Comment by kilograham** [comment]
closing awaiting PR
