### ISSUE TITLE
no way to abort/stop wifi scan

### ISSUE THREAD

**Issue by MrJake222** [raspberrypi/pico-sdk#1561]
My array is limited. There is no way to stop receiving results from callback.

**Comment by peterharperuk** [comment]
Wrong repo https://github.com/georgerobotics/cyw43-driver

**Comment by peterharperuk** [comment]
Please raise this against the correct repo. You are right that the api is not great. There should probably be a cancel which requires sending the "escan" message to the wifi firmware with the action set to 3 (abort)

**Comment by peterharperuk** [comment]
https://github.com/georgerobotics/cyw43-driver/issues/101
