### ISSUE TITLE
no wifi scan complete callback

### ISSUE THREAD

**Issue by MrJake222** [raspberrypi/pico-sdk#1562]
currently you need to do busy waiting for the scan to complete. This is not optimal in RTOS setups. There should be a callback when the scan is finished.

**Comment by peterharperuk** [comment]
How would you defined "complete"? You don't need to block at all, just scan for a set time and it will keep returning results. Also you have raised this against the pico-sdk which doesn't maintain this code https://github.com/georgerobotics/cyw43-driver. Closing as not an issue.
