### ISSUE TITLE
Include library to generate tones

### ISSUE THREAD

**Issue by jcarranz97** [raspberrypi/pico-sdk#1568]
I would be nice to have a library that generates tones inside the pico-sdk.

A lot of people is familiar with the [`tone()`](https://www.arduino.cc/reference/en/language/functions/advanced-io/tone/) function from Arduino which simplifies a lot the process of including a speaker or buzzer in your projects.

**Comment by lurch** [comment]
Closing, as the linked PR #1569 has been closed too.
See https://github.com/raspberrypi/pico-extras/pull/70 instead.
