### ISSUE TITLE
hardware/clock.h lists wrong definition for auxsrc XOSC for clk_sys

### ISSUE THREAD

**Issue by dthomas981** [raspberrypi/pico-sdk#1570]
https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2_common/hardware_clocks/include/hardware/clocks.h#L57

Documentation for the auxiliary clock sources in hardware/clocks.h has an error. The XOSC row in the table should list CLOCKS_CLK_SYS_CTRL_AUXSRC_VALUE_XOSC_CLKSRC in the clk_sys column but instead lists CLOCKS_CLK_SYS_CTRL_AUXSRC_VALUE_ROSC_CLKSRC.

This is just a documentation error; the actual definition is correct.
https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2040/hardware_regs/include/hardware/regs/clocks.h#L564

**Comment by lurch** [comment]
Fixed in develop.
