### ISSUE TITLE
adc_read() not checking for error conditions

### ISSUE THREAD

**Issue by ruehlchris** [raspberrypi/pico-sdk#1575]
Hi,

while testing the ADC single read I become aware that the current implementation not check for error conditions, only
look for the ADC_CS_READY_BITS.

I suggest to change the return value from a uint32_t to int32_t and return a negative value if
ADC_CS_ERR_BITS or ADC_CS_ERR_STICKY_BITS had been raised.

Here is what I used in my implementation.

[int32_t_adc_read.patch.gz](https://github.com/raspberrypi/pico-sdk/files/13575534/int32_t_adc_read.patch.gz)

You may consider to change the implementation.

Chris

**Comment by lurch** [comment]
@ruehlchris If you're suggesting a code-change, it's generally better to do that by submitting a Pull Request to the `develop` branch, than to attach a `.patch.gz` file to an Issue.

**Comment by ruehlchris** [comment]
Thanks,

I will have pull request ready soon.
