### ISSUE TITLE
can give altcp_tls more entropy

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-sdk#1577]
The altcp_tls api is the easiest way to use tls in the sdk. It's using out random number generator but we can pass in more entropy with the following macros.

#ifndef ALTCP_MBEDTLS_ENTROPY_PTR
#define ALTCP_MBEDTLS_ENTROPY_PTR   NULL
#endif
#ifndef ALTCP_MBEDTLS_ENTROPY_LEN
#define ALTCP_MBEDTLS_ENTROPY_LEN   0
#endif

Suggest we pass in some randomness from cmake so at least it's different per build?

**Comment by kilograham** [comment]
Not convinced that some build time entropy (possibly per configuration) really adds much?
