### ISSUE TITLE
CWE-686 in tools/elf2uf2/main.cpp:132

### ISSUE THREAD

**Issue by tjko** [raspberrypi/pico-sdk#1584]
Github code scanning is flagging CWE-686 in _tools/elf2uf2/main.cpp:132_

```
This argument should be of type 'void *' but is of type 'unsigned int'.
CodeQL
```

**Comment by tjko** [comment]
Looking the other other similar calls, I updated the pull request to use `%08x` as that seems to match how addresses are printed in the surrounding code...

**Comment by kilograham** [comment]
merged into develop
