### ISSUE TITLE
clock speed changes vs. capacitance vs. vreg voltage

### ISSUE THREAD

**Issue by canique** [raspberrypi/pico-sdk#1593]
Hardware: Raspberry Pico board
Power Supply: Anker PowerPort 6 with only the Raspberry Pico board connected

Test Case: Changing the sys clock from 48MHz USB PLL to 125 MHz SYS PLL

I have noticed that while executing the SDK function clock_configure() the system sometimes halts right at the point where the clock changes from the ring oscillator (intermediate step in the SDK function) to the target source (=SYS PLL) - that is line 98 in https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_clocks/clocks.c
The clock malfunction then leads to a watchdog reset.

The issue is related to the Anker PowerPort 6 since it neither occurs with an Apple charger nor with a Rocoren USB charger.

Nevertheless do I have some questions regarding this issue:

1. Does the Pico need additional capacitance on the 5V or 3V3 rail when the buck/boost converter is bypassed (in my case by an LDO)?
2. Should the VREG voltage be temporarily increased to 1.2V before doing big clock steps in clock_configure() - e.g. from 6 MHz ROSC to 125 MHz PLL?
3. Should big clock steps be splitted into smaller ones? I'm asking because STM32 devices running at a low voltage e.g. need about 5us at a certain clockspeed before switching to a higher one - to avoid an undervoltage situation.

Based on my tests it seems that splitting the ROSC -> PLL jump into smaller steps, by first using a bigger clock divider, then waiting a couple of cycles, then reducing the divider, then waiting again etc. seems to fix the issue - even with the Anker PowerPort 6.
What I also did was to increase the VREG voltage to 1.2V before doing the sysclock speed change.

What I also observed, though, during this procedure, was increased noise.

**Comment by peterharperuk** [comment]
I think you should post your questions in the forum as they don't appear to be related to pico-sdk https://forums.raspberrypi.com/viewforum.php?f=144
