### ISSUE TITLE
bump TinyUSB to latest upstream release

### ISSUE THREAD

**Issue by kilograham** [raspberrypi/pico-sdk#161]
We will at least try to get this in for 1.0.2 unless there are issues in which case we'll move to 1.0.3

**Comment by lurch** [comment]
Links to https://github.com/raspberrypi/pico-sdk/issues/85#issuecomment-778049788

**Comment by kilograham** [comment]
we have decided not to do this for 1.0.2 release, because we will need some upstream changes

**Comment by lurch** [comment]
Links to #73 also

**Comment by kilograham** [comment]
Fixed by #462

**Comment by kilograham** [comment]
merged
