### ISSUE TITLE
Get the SDK and exemples: Failure to download and initialise submodule

### ISSUE THREAD

**Issue by samdestroy3** [raspberrypi/pico-sdk#1647]
In section 2.1: Get the SDK and examples.

$ git clone https://github.com/raspberrypi/pico-sdk.git --branch master
$ cd pico-sdk
$ git submodule update --init

The command submodule update --init does not work.
![image](https://github.com/raspberrypi/pico-sdk/assets/9980713/fe2b5421-35af-4f90-ba8a-01be313f0df9)

**Comment by lurch** [comment]
I just tested and it works fine here - maybe you just had a temporary network glitch? :shrug: 

![Screenshot from 2024-02-25 01-55-11](https://github.com/raspberrypi/pico-sdk/assets/476186/a4b795fe-0b5c-43de-82d5-c65637f48bb5)

**Comment by samdestroy3** [comment]
Thank's for the validation. It may be as you said a network issues. I'm still having the issue. I Will try on an other network
