### ISSUE TITLE
[Pico W] Vendor specific host implementation 

### ISSUE THREAD

**Issue by Docfch** [raspberrypi/pico-sdk#1654]
Hello,

I have three interconnected hubs and on each hub I have connected an STM32 whose USB is in vendor-specific device mode. I want to plug it to a pico w to establish wifi communication through usb(see image above).

Is there an example on vendor specific host implementation or tell me how can i build it?

Thanks.

![image](https://github.com/raspberrypi/pico-sdk/assets/84841796/7ccf0cc5-4d97-4b9b-87d5-fadc2428642f)

**Comment by peterharperuk** [comment]
Details of the tinyusb examples are in the readme here https://github.com/raspberrypi/pico-examples/blob/master/README.md
and https://github.com/hathach/tinyusb/tree/master/examples/host
This sounds complicated, I doubt there's an example that does exactly what you want.
