### ISSUE TITLE
Update the minimum CMake requirements for pioasm

### ISSUE THREAD

**Issue by ondono** [raspberrypi/pico-sdk#1655]
Not sure what the plans are from CMake, but there's a constant deprecation warning when building that gets triggered because the minimum CMake version listed in pioasm's CMakeLists.txt is 3.4.

 Just wanted to raise the issue in case there's second order consequences from bumping this to >3.5.

**Comment by Ectalite** [comment]
Was fixed in https://github.com/raspberrypi/pico-sdk/pull/1546

**Comment by kilograham** [comment]
fix is in develop
