### ISSUE TITLE
dma_timer_set_fraction() inline docs refer to the fraction as a divider, but actually it's a multiplier

### ISSUE THREAD

**Issue by myklemykle** [raspberrypi/pico-sdk#1677]
Calling the fraction a divider insinuates that this function is analogous to, for instance, pwm_config_set_clkdiv_int_frac() . 
But that function divides clk_sys by a fraction, while dma_timer_set_fraction() multiplies clk_sys by a fraction. 

I find it a little bit counterintuitive that RP2040 scales DMA timers with a multiplier and PWM timers with a divider, but that's what the datasheet says it does.

**Comment by lurch** [comment]
Links to #1678

**Comment by kilograham** [comment]
#1678 merged
