### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by chaari02** [raspberrypi/pico-sdk#1681]
im trying to send data to mosquitto broker but i just can't seem to find the correct way how .Is there an example or something i can use ?

**Comment by lurch** [comment]
@peterharperuk Should this be moved to the pico-examples repo?

**Comment by peterharperuk** [comment]
Yes, probably. I do have an example for mqtt but I can't push it yet.

**Comment by chaari02** [comment]
Yes please add an MQTT example because im facing a problem. I can't figure
out what ip adress to put to receive data through mosquitto broker

**Comment by peterharperuk** [comment]
I suggest you do a dns lookup for the mqtt server you're trying to talk to. Closing this as you're in the wrong repo for examples
