### ISSUE TITLE
potentially unredistributable files in src/rp2_common/pico_btstack/

### ISSUE THREAD

**Issue by josch** [raspberrypi/pico-sdk#1695]
Hi,

I'm not a lawyer, so there might actually be no problem. I was made aware of this problem by Thorsten Alteholz who reviewed my Debian packaging of pico-sdk. The files inside `src/rp2_common/pico_btstack` are distributed under the following terms:

```
 “BlueKitchen” shall refer to BlueKitchen GmbH.
 “Raspberry Pi” shall refer to Raspberry Pi Ltd.
 “Product” shall refer to Raspberry Pi hardware products Raspberry Pi Pico W or Raspberry Pi Pico WH.
 “Customer” means any purchaser of a Product.
 “Customer Products” means products manufactured or distributed by Customers which use or are derived from Products.
 
 Raspberry Pi grants to the Customer a non-exclusive, non-transferable, non-sublicensable, irrevocable, perpetual
 and worldwide licence to use, copy, store, develop, modify, and transmit BTstack in order to use BTstack with or
 integrate BTstack into Products or Customer Products, and distribute BTstack as part of these Products or
 Customer Products or their related documentation or SDKs.
 [...]
```

So essentially, the right to copy, store and transmit BTstack is only granted to "Customers" which are defined as "purchaser of a Product". Github.com, which you are using to host this code, probably did not purchase any product, so they are probably not a customer and are thus not granted the permission to copy, store or transmit BTstack.

Or is the copyright information maybe incorrect and other terms apply to it?

Thanks!

**Comment by kilograham** [comment]
Also not a lawyer, but FYI: The license here refers to use of BTstack itself. BTstack is not included in the pico-sdk repository; it is a sub-module (in github) and is licensed with these terms https://github.com/bluekitchen/btstack/blob/master/LICENSE

The files in the `src/rp2_common/pico_btstack` are not part of BTstack, and are licensed under the regular BSD-3-Clause license of the SDK 
cc @ghollingworth @mringwal

**Comment by josch** [comment]
Thank you for looking into this! The git submodule is located under `lib/btstack`. If the files in `src/rp2_common/pico_btstack` are licensed under BSD, what is the meaning of this `LICENSE` file?

https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_btstack/LICENSE.RP

**Comment by josch** [comment]
I now read that it actually says exactly that in `src/rp2_common/pico_btstack/doc.h`:

> A supplemental license for BTstack (in addition to the stock BTstack licensing terms) is provided here https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_btstack/LICENSE.RP

**Comment by josch** [comment]
Closing, because there is no bug, just a misunderstanding about what source code the `LICENSE.RP` file actually applies to.
