### ISSUE TITLE
.wrap_target at the end of a PIO program is allowed, but generates bad code

### ISSUE THREAD

**Issue by davidgiven** [raspberrypi/pico-sdk#1712]
I wanted a program which ran once and halted, spinning forever until explicitly restarted by code. So I wrote this:

```
.program test
    nop
    .wrap_target
    .wrap
```

And I got this:

```
#define test_wrap_target 1
#define test_wrap 0
```

This is _technically_ correct. After the instruction at address 1 (the nop) is complete, the program counter is moved to... the address after. Which is correct because that's where I put the `.wrap_target`, but is meaningless.

What's happened here is that `.wrap_target` _looks_ like it's an instruction which gets jumped to, but it's not. It just labels the next instruction, and the end of the program is not an instruction. This was a mistake on my part, but ideally the assembler should have caught this and complained that what I was trying to do wasn't valid. I only realised what was going on once I looked at the generated code.

Feature request: please spot when I do this and error out.

Thanks!

**Comment by kilograham** [comment]
fixed

**Comment by davidgiven** [comment]
Thank you!
