### ISSUE TITLE
HARDFAULT HANDLER IN PICO-SDK !!!

### ISSUE THREAD

**Issue by ParthParekh01** [raspberrypi/pico-sdk#1727]
Hello everyone,

I'm encountering a hardfault issue with my Raspberry Pi Pico SDK project. My controller gets stuck in a hardfault state, and I am unsure how to handle it properly. Ideally, I would expect the controller to reset itself after a hardfault, but instead, it remains stuck, requiring a manual reset to resume operation.

Here are some details of my setup:

Device: Raspberry Pi Pico W
Development Environment: Arduino IDE 2.0
SDK Version: Raspberry Pi Pico SDK 1.5.1
Debugging Tool: Official Raspberry Pi Debug Probe

Has anyone else faced a similar issue, or does anyone know of an implementation of isr_hardfault in the Raspberry Pi Pico SDK that I can utilize to handle this more effectively? Any insights or suggestions on resolving this would be greatly appreciated.

Below is the provided hardfault log .
![hardfault_img](https://github.com/raspberrypi/pico-sdk/assets/172360865/c759c8a3-d662-4a5b-a132-681916b634e8)

My major concern is regarding the IMPLEMENTATION OF HARDFAULT HANDLER IN PICO-SDK .

Thank you!

**Comment by peterharperuk** [comment]
This is a forum for issues. Try posting questions to the forum https://forums.raspberrypi.com/viewforum.php?f=145
However I suggest you look into the use of watchdogs https://github.com/raspberrypi/pico-examples/blob/master/watchdog/hello_watchdog/hello_watchdog.c
