### ISSUE TITLE
hard_assert in initialise_rand() when all perf counters in use

### ISSUE THREAD

**Issue by roliver-rpi** [raspberrypi/pico-sdk#1733]
pico_rand will [hard_assert](https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2_common/pico_rand/rand.c#L233) when attempting to initialise_rand() if it is unable to find any bus fabric performance counters that are not in their reset state.

**Comment by kilograham** [comment]
See

```
// PICO_CONFIG: PICO_RAND_ENTROPY_SRC_BUS_PERF_COUNTER, Enable/disable use of a bus performance counter as an entropy source, type=bool, default=1, group=pico_rand
#ifndef PICO_RAND_ENTROPY_SRC_BUS_PERF_COUNTER
#define PICO_RAND_ENTROPY_SRC_BUS_PERF_COUNTER 1
#endif
```

You can turn off use of a perf counter as an entropy source by setting PICO_RAND_ENTROPY_SRC_BUS_PERF_COUNTER=0 in your compile definitions
