### ISSUE TITLE
rtc_enable_alarm(void) is static

### ISSUE THREAD

**Issue by astrorafael** [raspberrypi/pico-sdk#174]
Hi,
When playing with the RTC, I found that, although `rtc_disable_alarm()` is exported in the `hardware/rtc.h` header file, its counterpart `rtc_enable_alarm()` is not. It would be a pity having to duplicate this code in my software.
This is trivial to fix, I can do an fork and pull request if necessary.

**Comment by lurch** [comment]
Yeah, this also means that https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__rtc.html lists `rtc_disable_alarm` but doesn't list `rtc_enable_alarm` !

**Comment by lurch** [comment]
Fixed by #199 (this can be closed now, I dunno why GitHub didn't auto-close it?)
