### ISSUE TITLE
Enable WPA3 on Pico-W

### ISSUE THREAD

**Issue by B3rn475** [raspberrypi/pico-sdk#1743]
What is the correct way to enable WPA3 in Pico-W boards?

The [official website](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) reports that the Pico-W supports WPA3, but via the SDK it is only possible to enable WPA, WPA2 and WPA/WPA2 mixed mode.

**Comment by peterharperuk** [comment]
Yes it supports WPA3. The correct way is to add the WPA3 changes that are missing.

**Comment by B3rn475** [comment]
That would be great.

The WPA2 limitation in the IoT/Home Automation space is problematic from a security standpoint.

Adding support for WPA3 would definitely help the integration of Pico-W.

Thank you for taking a stab at it.

**Comment by peterharperuk** [comment]
All the changes needed are in the driver, so closing this and using the other issue you raised here https://github.com/georgerobotics/cyw43-driver/issues/118
