### ISSUE TITLE
Usage of printf for cyw43-spi

### ISSUE THREAD

**Issue by felixdoerre** [raspberrypi/pico-sdk#1744]
Currently the cyw43 spi implementation has a hard dependency on `printf`, here (and another one a few lines lower).

https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L501

I suggest to replace these `printf`-calls with the `CYW43_PRINTF` macro already available in cyw43-code, so binaries that include the cyw43 driver and don't require printf are not forced to pull it in.

**Comment by kilograham** [comment]
is this fixed?

**Comment by felixdoerre** [comment]
There is an open pull request #1745 that has not yet been merged.

**Comment by felixdoerre** [comment]
#1745 has been merged now. Thanks.
