### ISSUE TITLE
double_v1_rom_shim.S does not allow non-GPL sublicensing/distribution

### ISSUE THREAD

**Issue by recursivenomad** [raspberrypi/pico-sdk#1748]
I'm working on building a custom Debug Probe, and was auditing the SDK's licenses for files my compiler touches during building.

[`double_v1_rom_shim.S`](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_double/double_v1_rom_shim.S) is copywritten by Mark Owen under GPLv2, but contains an alternate sublicense through Raspberry Pi.  However, this sublicense only permits _use_ of the software (specifically only on a Raspberry Pi Pico device), but it does not permit recipients to sublicense or distribute this software (such as in a firmware binary to end-users).

Is it possible to reword this sublicense with more conventional language so that it grants recipients permission to sublicense & distribute without having to resort to the copyleft of GPLv2?

Additionally, would it be relevant to expand the restrictiont to allow usage on all RP2040 devices, rather than exlusively the Pico?

**Comment by kilograham** [comment]
thank you; that was the incorrect license (as used by the bootrom code itself, rather than the SDK) i have replaced

merged into devleop
