### ISSUE TITLE
Use of #define LWIP_SINGLE_NETIF 1 by default on Pico W

### ISSUE THREAD

**Issue by brizzolazzi** [raspberrypi/pico-sdk#1752]
For minimalism reasons it might be useful to enable by default the LWIP_SINGLE_NETIF in lwipopts.h.

At the moment the SDK does not compile with that option.

**Comment by peterharperuk** [comment]
I can't see any issues in the SDK. It seems to be a problem in pico-examples and the cyw43-driver.
https://github.com/raspberrypi/pico-examples/issues/514
https://github.com/georgerobotics/cyw43-driver/issues/124
