### ISSUE TITLE
__not_in_flash_func doesn't set noinline

### ISSUE THREAD

**Issue by michalelektryk** [raspberrypi/pico-sdk#1758]
So I wanted to move part of core1 code to RAM by factoring it into its own function but the function got inlined, effectively putting it back into flash. The current workaround is to put function into a different compilation unit, but that's not the best solution.

**Comment by kilograham** [comment]
Um, `__no_inline_not_in_flash_func` ?

**Comment by michalelektryk** [comment]
One day I'll learn that being an idiot isn't curable.... Sorry for time wasted
