### ISSUE TITLE
Can not find marco CLOCKS_PER_SEC in runtime.c

### ISSUE THREAD

**Issue by sgstreet** [raspberrypi/pico-sdk#1780]
In some circumstances the CLOCKS_PER_SEC is undefined resulting in the following error:

```
/home/stephen/Workspace/pico-toolkit-dev/pico-sdk/src/rp2_common/pico_runtime/runtime.c:242:83: error: 'CLOCKS_PER_SEC' undeclared (first use in this function); did you mean 'CLOCKS_BASE'?
  242 |     tms->tms_utime = (clock_t)(to_us_since_boot(get_absolute_time()) / (1000000 / CLOCKS_PER_SEC));
      |                                                                                   ^~~~~~~~~~~~~~
      |                                                                                   CLOCKS_BASE
```
This occurs because CLOCKS_PER_SEC is defined [time.h](https://github.com/bminor/newlib/blob/d001c01a7c5277194e7f8891f0228a2e3c4c64e1/newlib/libc/include/time.h#L21) but the pico-sdk [runtime.c](https://github.com/sgstreet/pico-sdk/blob/45984e276f85aa24d33aa0ab62ed1e6df96a0784/src/rp2_common/pico_runtime/runtime.c#L9) does not include it.

**Comment by kilograham** [comment]
fixed
