### ISSUE TITLE
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt. Please visit http://www.java.com for information on installing Java.

### ISSUE THREAD

**Issue by daklekar** [raspberrypi/pico-sdk#1783]
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

i keep getting this error for the pico setup.
I am. running the pico_setup.sh on a mac book

**Comment by daklekar** [comment]
[mac_script.txt](https://github.com/user-attachments/files/16553383/mac_script.txt)

this script worked for me on mac

**Comment by kilograham** [comment]
yeah pico_setuo.sh is only supported on Raspberry Pi
