### ISSUE TITLE
Compilation warnings in  multicore.c: when PICO_CORE1_STACK_SIZE=0x0 

### ISSUE THREAD

**Issue by UKTailwind** [raspberrypi/pico-sdk#1803]
When explicitly creating a memory region to use multicore_launch_core1_with_stack it is reasonable to then set the size of the default core1 stack to zero in the cmake file. This creates multiple compilation warnings in multicore.c (-Wall). Not a big deal but is would be nice to have the compilation run with no warnings.

**Comment by kilograham** [comment]
merged into develop
