### ISSUE TITLE
"pico/stdlib.h" no longer provides `set_sys_clock_khz` (moved to "hardware/clocks.h" in sdk v2.0.0)

### ISSUE THREAD

**Issue by toymil** [raspberrypi/pico-sdk#1806]
*Pico C/C++ SDK* (pdf version, 2024-08-09, c274ff8-clean) list `set_sys_clock_khz` as a function included by "pico/stdlib.h".  However, calling it will result in `warning: implicit declaration of function 'set_sys_clock_khz'`.

After a little digging it seems like the function was in "pico/stdlib.h" on sdk v1.5.1, but moved to "hardware/clocks.h" in sdk v2.0.0, and is not pulled in by "pico/stdlib.h".

**Comment by lurch** [comment]
Ahh, this was actually a Doxygen-error, good catch!
#1808 will fix it.

**Comment by kilograham** [comment]
merged into develop
