### ISSUE TITLE
SDK2.0 Missing .hex file with pico_add_extra_outputs()

### ISSUE THREAD

**Issue by ecurtz** [raspberrypi/pico-sdk#1829]
pico_add_extra_outputs() in CMakeLists.txt is no longer generating the .hex versions, only the .bin and .uf2. All of the flags, including PICO_32BIT appear to be set correctly but pico_add_hex_output() is not being invoked for some reason.

forum thread here: https://forums.raspberrypi.com/viewtopic.php?t=375084

**Comment by kilograham** [comment]
fixed in develop

**Comment by kilograham** [comment]
fixed in develop
