### ISSUE TITLE
bazel: including bootloader targets in `link_extra_lib` results in a dependency cycle

### ISSUE THREAD

**Issue by cramertj** [raspberrypi/pico-sdk#1853]
The bazel bootloader targets (e.g. @@pico-sdk~//src/rp2040/boot_stage2:boot_stage2_elf_actual) get built with `link_extra_lib` in their deps, so including them in the `link_extra_lib` list for other binaries causes a dependency cycle. This cycle should be broken by removing `link_extra_lib` dependencies when building bootloader targets.

PR incoming.

**Comment by kilograham** [comment]
merged into develop
