### ISSUE TITLE
Compiling with --print-memory-usage always shows 100% RAM?

### ISSUE THREAD

**Issue by warcow105** [raspberrypi/pico-sdk#1871]
SDK version 2.0
I have tested using a project that I upgraded to the new SDK version as well as a fresh HelloWorld that I made using the vscode plugin and both report 100% ram usage with set_property(TARGET hellotest APPEND_STRING PROPERTY LINK_FLAGS "-Wl,--print-memory-usage")

I didn't have this issue on 1.5.1

**Comment by warcow105** [comment]
Thanks @kilograham , I tested your patch on my system and all seems to be good in the world now.

**Comment by kilograham** [comment]
merged into develop
