### ISSUE TITLE
Wrong PICO_FLASH_SIZE_BYTES for Tiny2350 

### ISSUE THREAD

**Issue by polhenarejos** [raspberrypi/pico-sdk#1884]
Pimoroni's Tiny2350 has 4MB of flash room, not 8, as they describe in their website:

https://shop.pimoroni.com/products/tiny-2350?variant=42092638699603

I have a Tiny2350 and I can confirm that `picotool` reports 4MB.

https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/boards/include/boards/pimoroni_tiny2350.h#L89

I spoke to them but I did not get any answer and not sure how to proceed or who is the responsible for maintaining the board's header definition.

**Comment by lurch** [comment]
I already fixed this as part of https://github.com/raspberrypi/pico-sdk/pull/1814 :grinning: 
Fixed on `develop` branch.
