### ISSUE TITLE
Comment in pico_configure_ip4_address uses wrong definition names

### ISSUE THREAD

**Issue by mattmyne** [raspberrypi/pico-sdk#1891]
A comment in CMakeLists.txt `pico_configure_ip4_address` function incorrectly references the `CYW43_DEFAULT_IP_AP_ADDRESS` compile definition name as `CYW43_DEFAULT_AP_IP_ADDRESS`.

This should be fixed to avoid user confusion when setting an alternative IP in AP mode.

**Comment by mattmyne** [comment]
Added PR #1892 that also updates the default station IP definition names, from `CYW43_DEFAULT_IP_...` to `CYW43_DEFAULT_IP_STA_...`

**Comment by kilograham** [comment]
merged into develop
