### ISSUE TITLE
system_RP2350.h typos

### ISSUE THREAD

**Issue by metebalci** [raspberrypi/pico-sdk#1909]
In src/rp2_common/cmsis/stub/CMSIS/Device/RP2350/Include/system_RP2350.h, the file header and the macro definition (_CMSIS_SYSTEM_RP2040_H) still refers to RP2040.

**Comment by lurch** [comment]
Well spotted! Would you like to submit a Pull Request against the `develop` branch?

**Comment by kilograham** [comment]
merged into develop
