### ISSUE TITLE
rp2350_chip_version manufacturer assertion failure

### ISSUE THREAD

**Issue by trejan** [raspberrypi/pico-sdk#1935]
[Report on the forum](https://forums.raspberrypi.com/viewtopic.php?t=376669) that rp2350_chip_version() fails the manufacturer assertion.

[RP2350 SYSINFO_CHIP_ID_MANUFACTURER_BITS](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2350/hardware_regs/include/hardware/regs/sysinfo.h#L38) masks off the LSB "stop bit" but the assertion is comparing against a [MANUFACTURER_RPI value that wasn't masked](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2350/pico_platform/platform.c#L31). MANUFACTURER_RPI should be 0x926.

RP2040 docs don't mention the stop bit and don't mask it. Presumably the stop bit also exists here but undocumented as JEP-106 indicates the identity code values are 7-bit with parity bit.

**Comment by kilograham** [comment]
fixed in develop
