### ISSUE TITLE
(minor issue) incorrect comment on src/rp2_common/hardware_uart/include/hardware/uart.h:229

### ISSUE THREAD

**Issue by DiarrheaMcgee** [raspberrypi/pico-sdk#1981]
it would seem that the documentation for this function has the param and return comments swapped
https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_uart/include/hardware/uart.h#L229

**Comment by lurch** [comment]
Already fixed on `develop` by #1828 :slightly_smiling_face:
