### ISSUE TITLE
Pimorni Pico Plus 2 W header file?

### ISSUE THREAD

**Issue by znmeb** [raspberrypi/pico-sdk#1985]
I don't see a header file in <https://github.com/raspberrypi/pico-sdk/tree/master/src/boards/include/boards> for the new Pimorni Pico Plus 2 W <https://shop.pimoroni.com/products/pimoroni-pico-plus-2-w?variant=42182811942995>. Is that board on the road map?

**Comment by peterharperuk** [comment]
You'll have to contact Pimoroni. It would have to use the develop branch initially.

**Comment by znmeb** [comment]
Thanks! I opened an issue on their 2350 repo https://github.com/pimoroni/pimoroni-pico-rp2350/issues/15.
