### ISSUE TITLE
GCC 14.1 error while compiling boot2.S for W25x10

### ISSUE THREAD

**Issue by earlephilhower** [raspberrypi/pico-sdk#1999]
For the `arduino-pico` project we support building apps in Arduino using ARM or RISC-V.  We use GCC 14.1 for both architectures to keep our sanity while debugging things.

GCC 14 seems to barf on double-number labels like "00:" present in a single .S file, giving the following error:
````
.../pico-sdk/src/rp2040/boot_stage2/boot2_w25x10cl.S: Assembler messages:
.../pico-sdk/src/rp2040/boot_stage2/boot2_w25x10cl.S:147: Error: junk at end of line, first unrecognized character is `0'
.../pico-sdk/src/rp2040/boot_stage2/boot2_w25x10cl.S:150: Error: garbage following instruction -- `beq 00b'
````

The same code builds under ARM GCC 12, so this is something that's changed in the way the GNU assembler does things in the intervening releases.  This is a simple loop target, so it's a trivial fix.

(Reported by @morio in https://github.com/earlephilhower/pico-quick-toolchain/issues/65)

**Comment by lurch** [comment]
Fixed in `develop`
