### ISSUE TITLE
Add XIP cache management routines

### ISSUE THREAD

**Issue by earlephilhower** [raspberrypi/pico-sdk#2005]
The XIP cache works really well except in certain cases involving [PSRAM and flash updates](https://forums.raspberrypi.com/viewtopic.php?t=378249) with a really [non-obvious (IMHO) workaround](https://forums.raspberrypi.com/viewtopic.php?t=378249#p2263677).

Because cache cleaning needs some special magic to work with PSRAM as discussed in the links above, it may make sense to add  some XIP cache management operations to the SDK (especially "XIP Clean").  Right now we have `arduino-pico`, `CircuitPython` and `MicroPython` all implementing the same XIP cache management code separately.  It would be cleaner and safer to factor that out up into the SDK.

I imagine something as simple as
* `xip_cache_clean`
* `xip_cache_invalidate`
* `xip_cache_invalidate_range` (?)

might be all that's needed, but maybe others have additional requirements?

Kind-of related to #1983, but at a higher level.

**Comment by will-v-pi** [comment]
Just to add to this, a pin function would also be useful

- `xip_cache_pin_range`

**Comment by lurch** [comment]
#2005 has now been merged into `develop`

**Comment by earlephilhower** [comment]
Awesome, thank you all!
