### ISSUE TITLE
Check that #define-d PIN combinations make sense at compile-time

### ISSUE THREAD

**Issue by lurch** [raspberrypi/pico-sdk#204]
(as initially suggested in #192)

It might be nice to have a compile-time #error if you give an invalid combination of UART_DEFAULT settings? e.g. setting {PICO_DEFAULT_UART=0, PICO_DEFAULT_UART_TX_PIN=13} (invalid because GPIO13 is UART0 **RX**) or {PICO_DEFAULT_UART=1, PICO_DEFAULT_UART_TX_PIN=0} (invalid because GPIO0 is **UART0** TX).
(with similar things being done for I2C and SPI pins too)

**Comment by kilograham** [comment]
#1724 has been merged into develop
