### ISSUE TITLE
CYW43 PIO SPI driver has hardcoded ARM assembly, breaks for RISC-V builds

### ISSUE THREAD

**Issue by earlephilhower** [raspberrypi/pico-sdk#2044]
There's hardcoded ARM assembly in the WiFi software SPI driver which causes RISC-V builds to fail:
https://github.com/raspberrypi/pico-sdk/blob/1b64cac8d697cdfda50527dfcff58c083f55429b/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L81-L85

**Comment by kilograham** [comment]
merged into develop
