### ISSUE TITLE
Faulty parameter check in 'hardware/pwm.h'

### ISSUE THREAD

**Issue by newbrain** [raspberrypi/pico-sdk#2076]
A minor fault in parameter checking for `pwm_irqn_get_status_mask()`.

Line 764 of `hardware/pwm.h` reads:
https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2_common/hardware_pwm/include/hardware/pwm.h#L764

The check should be against `NUM_PWM_IRQS` (2 for RP2350, 1 for RP2040) instead of `NUM_DMA_IRQS` (4 for RP2350, 2 for RP2040), as all the other similar ones.

SDK version: 2.0.0
The issue is still present in _main_ and _develop_ branches as of today.

**Comment by kilograham** [comment]
merged into develop
