### ISSUE TITLE
Ease integration of RTOS, we need cmsis-compatible exceptional handler naming or API to install exceptional handler in RAM

### ISSUE THREAD

**Issue by xiongyu0523** [raspberrypi/pico-sdk#211]
I'm porting Azure RTOS threadx to PICO and I can't submodule the threadx repo because I need to hook the pendsv and systick exceptional handlers. 

In crt0.S, the SDK declare as isr_pendsv and isr_systick which are private and not conform to CMSIS standard, so the cm0 processor port of Azure RTOS need to be modified. 

Or if you can provide a API similar to `irq_set_exclusive_handler` but work for all entries include 0-15 exceptional handlers. Then I can install by user code after main. This is also good.

Now, I can only modify the source of threadx to align with SDK naming, which is not flexible

**Comment by kilograham** [comment]
yes we plan to add ability to set exception handlers (an omission)

also we can make these public; we may not rename them, but at that point you can inject a header via cmake to rename them via #define.

**Comment by lurch** [comment]
Links to #21 and #127

**Comment by michael-ring** [comment]
Where can I put my vote that at least the cortex specific handlers get proper CMSIS names?

**Comment by kilograham** [comment]
Actually since these were private, we can likely rename them.

**Comment by michael-ring** [comment]
That would be really great! https://github.com/raspberrypi/pico-sdk/issues/21 has all necessary links to cmsis docs.

**Comment by xiongyu0523** [comment]
> yes we plan to add ability to set exception handlers (an omission)
> 
> also we can make these public; we may not rename them, but at that point you can inject a header via cmake to rename them via #define.

So your suggestion is to add below global macro definition in CMakeLists.txt to replace the symbol, right?

```
add_definitions(-DPendSV_Handler=isr_pendsv)
add_definitions(-DSysTick_Handler=isr_systick)
```

**Comment by kilograham** [comment]
that was an option that would have workedd - albeit ugly-ly - but i've decided to add the real names now

**Comment by kilograham** [comment]
(setting variables yes, via global CMake add_defitions - which is eveil - no!)

**Comment by xiongyu0523** [comment]
at least it works and I can now submodule my threadx repo without any change. I left this ticket open and let you decide when a better solution is ready

**Comment by michael-ring** [comment]
Could this be a candidate for Release 1.2?

**Comment by kilograham** [comment]
merged

**Comment by kilograham** [comment]
closing this for the ability to set exception handlers, see #21 if you want the CMSIS exception handler naming instead
