### ISSUE TITLE
SVD File -missing VTOR table under CPU

### ISSUE THREAD

**Issue by conkerkh** [raspberrypi/pico-sdk#22]
From SVD file specification under CPU section, vtorPresent is missing. According to the datasheet of RP2040 VTOR relocation using VTOR register is supported. Please add vtorPresent field set to 1 under CPU section.

[https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_cpu.html](url)

**Comment by Wren6991** [comment]
Note this is probably the reason it wasn't added:

> vtorPresent | Indicate whether the Vector Table Offset Register (VTOR) is implemented in Cortex-M0+ based devices. This tag is either set to true or false, 1 or 0. **If not specified, then VTOR is assumed to be present.**

Raised a PR to add this anyway as there's no need to be ambiguous

**Comment by Wren6991** [comment]
Now merged
