### ISSUE TITLE
stdio_uart does not work with uart1 

### ISSUE THREAD

**Issue by GordonD1980** [raspberrypi/pico-sdk#220]
You can set stdio_uart to use uart1 with stdio_uart_init_full() which creates a driver with uart1 and initiates uart1.
However stdio_uart_out_chars() and stdio_uart_in_chars() both use uart_default (uart0) rather than the UART reference in the driver causing the program to get stuck in uart_write_blocking() as it attempts to write chars to an un-initialised UART

**Comment by kilograham** [comment]
already fixed in develop branch
