### ISSUE TITLE
hello world example missing

### ISSUE THREAD

**Issue by albertvanderhorst** [raspberrypi/pico-sdk#246]
There is no hello world example in this kit. 
There is a pico-examples/hello_world subdirectory, but with its 
tree . 
 ...
    |   |   `-- progress.marks
    |   |-- Makefile
    |   `-- cmake_install.cmake
    `-- hello_usb.c

43 directories, 127 files

it cannot count as an hello world example, that is supposed to be the simplest of all.
There should be separate examples for hello_world on the uart and on the usb, and none of the two should be burdened with even the notion that there is an alternative to the communication channel choosen.

**Comment by aallan** [comment]
> There should be separate examples for `hello_world` on the uart and on the usb…

There are separate examples for UART and USB,

```
$ cd pico-examples/hello_world/
$ ls
total 8
drwxr-xr-x   5 aa  staff   160B 11 Mar 13:41 ./
drwxr-xr-x  34 aa  staff   1.1K 11 Mar 13:41 ../
-rw-r--r--   1 aa  staff    47B 11 Mar 13:41 CMakeLists.txt
drwxr-xr-x   4 aa  staff   128B 20 Jan 23:41 serial/
drwxr-xr-x   4 aa  staff   128B 11 Mar 13:41 usb/
$ ls serial/
total 16
drwxr-xr-x  4 aa  staff   128B 20 Jan 23:41 ./
drwxr-xr-x  5 aa  staff   160B 11 Mar 13:41 ../
-rw-r--r--  1 aa  staff   320B 20 Jan 23:41 CMakeLists.txt
-rw-r--r--  1 aa  staff   283B 20 Jan 23:41 hello_serial.c
$ ls usb/
total 16
drwxr-xr-x  4 aa  staff   128B 11 Mar 13:41 ./
drwxr-xr-x  5 aa  staff   160B 11 Mar 13:41 ../
-rw-r--r--  1 aa  staff   626B 11 Mar 13:41 CMakeLists.txt
-rw-r--r--  1 aa  staff   283B 20 Jan 23:41 hello_usb.c
$ 
```
the two examples are discussed in Chapter 4 of the [Getting Started](https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf) guide. Serial input (stdin) and output (stdout) can be directed to either serial UART or to USB CDC (USB serial) and it was therefore decided that this was the simplest way to present the material to new users.

> …and none of the two should be burdened with even the notion that there is an alternative to the communication channel choosen.

I don't agree.
