### ISSUE TITLE
pio_can_add_program and pio_add_program may not work for maximum size PIO program

### ISSUE THREAD

**Issue by kevinjwalters** [raspberrypi/pico-sdk#261]
I'm not famiIiar with this code but was flicking through it and perhaps this should be `<=` rather than `<`?

https://github.com/raspberrypi/pico-sdk/blob/786be7524aa3c7c5467faebc54fd7c4db077ae2e/src/rp2_common/hardware_pio/pio.c#L56-L57

This will probably only affect debug versions of the code/library?

**Comment by lurch** [comment]
Already fixed (on `develop` branch) by #236 :slightly_smiling_face:
