### ISSUE TITLE
Missing functionality: pad electrical controls

### ISSUE THREAD

**Issue by P33M** [raspberrypi/pico-sdk#290]
In the C SDK, gpio_set_pulls() is implemented but other pad controls are inaccessible - I don't see any SDK functions that control output drive strength, input hysteresis (schmitt triggering) or slew rate adjustment.

c.f. 2.19.4 in the rp2040 datasheet.

**Comment by lurch** [comment]
I guess [hardware_gpio](https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__gpio.html) would be the place to add this?

**Comment by kilograham** [comment]
Not going to make 1.2.0 unless someone wants to make a PR real quick?
