### ISSUE TITLE
stdio_usb.c does not compile

### ISSUE THREAD

**Issue by jmfloyd** [raspberrypi/pico-sdk#302]
Missing include file in file 
   src/rp2_common/pico_stdio_usb/stdio_usb.c

needs
#include "pico/stdio_usb.h"

**Comment by lurch** [comment]
Sounds like something hasn't been set up correctly. And we'll need a lot more info to figure out what's happened...
Which OS are you using? Which compiler are you using? Which instructions have you followed? What command-line were you using that failed? What other output do you see?

**Comment by kilograham** [comment]
no updates; closing
