### ISSUE TITLE
When tinyusb upstream repo will be used in the sdk?

### ISSUE THREAD

**Issue by kehribar** [raspberrypi/pico-sdk#303]
Hi All,

According to [1], official tinyusb repo is the way to go for latest features and for _less_ bugs.

But pico-sdk still uses https://github.com/raspberrypi/tinyusb even for the latest release issued yesterday. 

When this repo will start using https://github.com/hathach/tinyusb as a submodule?

Thanks.

[1] https://github.com/raspberrypi/tinyusb/issues/4#issuecomment-778849350

**Comment by lurch** [comment]
I believe it's on the todo list, but there's no ETA yet. See also #161

**Comment by luxedo** [comment]
I spent quite some time to understand why the default gamepad descriptor wasn't working  😆

**Comment by kilograham** [comment]
As @lurch says #161 which is in 1.2.0 which is the next feature release
