### ISSUE TITLE
Rust Pico SDK

### ISSUE THREAD

**Issue by AsafFisher** [raspberrypi/pico-sdk#33]
Hello!
I am about to implement this library with rust. 
Are there any helpful suggestions and tips? I thought about making it an FFI but decided to make it pure rust.
Also the name `pico-sdk-rs` sounds like a fine name?

**Comment by lurch** [comment]
I think @thejpster is starting to look at that? Probably worth collaborating... (unless, as a non Rust programmer, I've misunderstood?)

**Comment by AsafFisher** [comment]
Hello @thejpster!

**Comment by thejpster** [comment]
There is a Github organisation over at https://github.com/rp-rs and a Matrix channel #rp-rs if anyone wants to join in with Rust on the Pico / RP2040. I'd be very happy to talk to RPT folks about making something official too.
