### ISSUE TITLE
Missing memory layout in svd

### ISSUE THREAD

**Issue by Szpadel** [raspberrypi/pico-sdk#351]
I'm trying to implement USB driver in rust and I cannot find endpoint and buffer controll registers. It looks like there is nothing from base 0x5010000 to 0x5011000.
I confirmed that there should be controller structures in datasheet and are used in c implementation.

Am I missing something or there is some issue with svd?

**Comment by lurch** [comment]
I just checked, and I guess you're asking about the `USBCTRL_DPRAM` stuff? https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2040/hardware_regs/include/hardware/regs/addressmap.h#L65

The C SDK comprises some headers that are autogenerated ([hardware_regs](https://github.com/raspberrypi/pico-sdk/tree/master/src/rp2040/hardware_regs)), and some that are manually-edited ([hardware_structs](https://github.com/raspberrypi/pico-sdk/tree/master/src/rp2040/hardware_structs)) - the `hardware_structs` headers generally make use of things defined in the `hardware_regs` headers. The SVD file is also autogenerated.

The `USBCTRL_REGS` stuff appears in the autogenerated hardware_regs [headers](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2040/hardware_regs/include/hardware/regs/usb.h) and the [SVD file](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2040/hardware_regs/rp2040.svd), but the `USBCTRL_DPRAM` stuff only appears in the hand-edited [headers](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2040/hardware_structs/include/hardware/structs/usb.h) (and therefore not the SVD).

I know nothing about the USB controller in the RP2040, so pinging @liamfraser for advice on what can / should be added to the SVD file.
