### ISSUE TITLE
What is this shit haha ? -- BUG --

### ISSUE THREAD

**Issue by fannst** [raspberrypi/pico-sdk#355]
![Schermafdruk van 2021-04-23 21-08-04](https://user-images.githubusercontent.com/78303120/115919470-298c7100-a479-11eb-8530-4e820be65042.png)
![Schermafdruk van 2021-04-23 21-15-45](https://user-images.githubusercontent.com/78303120/115919480-2c876180-a479-11eb-88ec-87fb7c1a00cb.png)

So... Trying to boot my device from flash, so inspecting your code... I'm pretty sure 31 in base 10, does not fit in 2⁴-1

**Comment by kilograham** [comment]
RTFM

<img width="758" alt="Screen Shot 2021-04-23 at 2 30 42 PM" src="https://user-images.githubusercontent.com/575810/115920986-89b2f100-a440-11eb-964f-5d627c7ab9a1.png">
