### ISSUE TITLE
error in /common/pico_sync/include/pico/sem.h

### ISSUE THREAD

**Issue by PaulskPt** [raspberrypi/pico-sdk#357]
I am just a greenie in C++ but I think I encountered an error:

In the file pico-sdk/src/common/pico_sync/include/pico/sem.h, line 32, inside the typedef struct __packed_aligned semaphore{}
is defined: 'struct lock_core core;'
but in the same subfolder, in file lock_core.h, the structure defined in lines 23-29, is named 'lock_core_t'
so I think the the definition of the nested structure in sem.h should be written as: 'struct lock_core_t core;'

**Comment by lurch** [comment]
> in file lock_core.h, the structure defined in lines 23-29, is named 'lock_core_t'

Not quite. [lock_core.h](https://github.com/raspberrypi/pico-sdk/blob/master/src/common/pico_sync/include/pico/lock_core.h#L23) defines `lock_core_t` as a typedef for `struct lock_core`.
This means [sem.h](https://github.com/raspberrypi/pico-sdk/blob/master/src/common/pico_sync/include/pico/sem.h#L32) is able (AFAIK, I'm not a C expert either) to either use `struct lock_core core;` **or** `lock_core_t core;`.

There's lots of test-code in https://github.com/raspberrypi/pico-sdk/tree/master/test and https://github.com/raspberrypi/pico-examples and I'm fairly sure that some of that would fail to compile if there were errors with the types in the headers? :wink:
