### ISSUE TITLE
mutex_init() fails to initialize the 'owned' field

### ISSUE THREAD

**Issue by geurtv** [raspberrypi/pico-sdk#36]
mutex_init() fails to initialize the 'owned' field of mutex_t. So a malloc'ed mutex or a mutex on the stack is likely to be locked (owned != 0) after mutex_init.

Also 'owner' is not initialized. It might make sense to '#ifndef NDEBUG' initialize it to -1 (like mutex_exit).

**Comment by kilograham** [comment]
good catch - i've always used static mutexes so never noticed!

**Comment by kilograham** [comment]
merged into develop
