### ISSUE TITLE
For consistency reasons, add a function spi_get_baudrate()

### ISSUE THREAD

**Issue by Reneg973** [raspberrypi/pico-sdk#390]
There is a setter but no getter. Maybe sometimes required:

```
uint spi_get_baudrate(const spi_inst_t *spi)
{
  uint prescale = spi_get_hw(spi)->cpsr;
  uint postdiv = ((spi_get_hw(spi)->cr0  & SPI_SSPCR0_SCR_BITS) >> SPI_SSPCR0_SCR_LSB) + 1;
  return clock_get_hz(clk_peri) / (prescale * postdiv);
}

```

**Comment by Reneg973** [comment]
I know, and in my case it doesn't help. Therefore I wrote the function above. This entry is the proposal to insert it into the SDK.

**Comment by lurch** [comment]
Do you want to add this as a PR (against the `develop` branch) rather than just as an issue?

**Comment by Reneg973** [comment]
close, added PR #395
