### ISSUE TITLE
hardware/adc.h not found

### ISSUE THREAD

**Issue by Stubblet** [raspberrypi/pico-sdk#394]
I have setup visual code etc as per the documentation. All of the examples build clean from the IDE.

Simple programs of my own using gpio_init, gpio_set_dir etc.  which use "pico/stdlib.h" all work.  

When I try and include "hardware/adc.h" the ide and compiler complain:

![adc h 02](https://user-images.githubusercontent.com/55135494/117784655-b0906600-b23b-11eb-9703-fc408eaa3c28.jpg)

>>cannot open source file "hardware/adc.h". 

The intellisense function also does not show adc within the hardware hierarchy. 

![adc h](https://user-images.githubusercontent.com/55135494/117784255-45469400-b23b-11eb-8a12-9f7bda228f5a.jpg)

I have downloaded the latest SDK as of 11 May 2021 and built it from the SDK folder.

Its probably user error but none of my usual diagnostic techniques are revealing the problem.

Ideas ?

Andrew

**Comment by lurch** [comment]
Sounds like you've probably forgotten to add `hardware_adc` to your `CMakeLists.txt`? See https://github.com/raspberrypi/pico-examples/blob/master/adc/hello_adc/CMakeLists.txt for an example.

**Comment by Stubblet** [comment]
Indeed I had. That will teach me to come back to c programming after over a decade.

Much appreciated

Andrew
