### ISSUE TITLE
No windows support?

### ISSUE THREAD

**Issue by foxabilo** [raspberrypi/pico-sdk#4]
Hi, great that there is an SDK all done but how can I use my Windows based dev machine to compile code for the Pico?

**Comment by Antosik-dev** [comment]
Of course it does. You read in: [https://datasheets.raspberrypi.org/pico/getting_started_with_pico.pdf](datasheets) Chapter 8.1

**Comment by foxabilo** [comment]
Cheers! I thought I'd been through it all, wood for the trees, thank you.
