### ISSUE TITLE
add a board header for the Arduino Nano RP2040

### ISSUE THREAD

**Issue by 2bndy5** [raspberrypi/pico-sdk#424]
I could throw this together myself based on the available schematic, but I'm unsure about some things like the Flash SPI CLK divider to use... I don't know who on the @arduino team to ping about this (@facchinm ?). 

I don't want to overstep here. If this request is explicitly undesired, then I'll back off and close this issue.

My reason for wanting a _arduino_nano_rp2040.h_ in _/src/boards/include/boards/_ folder is because these board header files have proven extremely useful for 3rd-party libraries (that have incorporated native Pico SDK support) to choose a default set of pins in a rather agnostic way - leaving the actual choice of board to build for up to the user via `-DPICO_BOARD=<board_name>`.

**Comment by lurch** [comment]
> these board header files have proven extremely useful

That's nice to hear :smiley: Well done @kilograham ! :clap:
