### ISSUE TITLE
Please add PlatformIO integration

### ISSUE THREAD

**Issue by harry1453** [raspberrypi/pico-sdk#44]
I was requested to open this here.

Original issue: https://github.com/platformio/platformio-core/issues/3805

PlatformIO is a very popular build system, it would be awesome if the RP2040 and/or RPi Pico were targets.

**Comment by JamesH65** [comment]
I don't believe this is something we would do, we already use the Cortex debug extensions which work for us. Seems more like a job for the PlatformIO devs, they would be much more familiar with the process of adding a new platform to their system.

**Comment by blackketter** [comment]
> I don't believe this is something we would do, we already use the Cortex debug extensions which work for us. Seems more like a job for the PlatformIO devs, they would be much more familiar with the process of adding a new platform to their system.

There seems to be some confusion between the PlatformIO team (@JamesH65) and the RasPI team (@ivankravets)...

PlatformIO and Pico seem like a natural fit.  I hope that this can be worked out!

**Comment by monitorjbl** [comment]
This may not be the right place to ask about this but [PlatformIO](https://platformio.org/) is pretty popular for programming boards like the Pico. It makes it really easy to use VSCode to write and upload C++ code to Arduino boards, so being able to use it for the Pico would be awesome!

**Comment by aallan** [comment]
As @JamesH65 said upthread, this isn't something we're likely to look at ourselves. We're happy to answer questions from the PlatformIO devs if they want to add support.

**Comment by ivankravets** [comment]
Hi @aallan,

See an update at https://github.com/platformio/platformio-core/issues/3805#issuecomment-771551792

P.S: I've just sent you an email. Hope to chat soon.

**Comment by aallan** [comment]
> P.S: I've just sent you an email. Hope to chat soon.

So @ivankravets, it's @ghollingworth, who I think you're already talking to, that is the person you need to chat to about this.

**Comment by aallan** [comment]
As I said upthread we're happy to support your porting effort, and if you have any issues with doing that then you can use the [pico-feedback](https://github.com/raspberrypi/pico-feedback/issues) repo to communicate with our engineering team. 

However we are not going to work on this ourselves.

**Comment by Wiz-IO** [comment]
just experiment as beginning...
https://github.com/Wiz-IO/wizio-pico
