### ISSUE TITLE
Missing doxygen for next_striped_spin_lock_num

### ISSUE THREAD

**Issue by lurch** [raspberrypi/pico-sdk#445]
This function is [used in several places](https://github.com/raspberrypi/pico-sdk/search?q=next_striped_spin_lock_num&type=code) but is currently [missing a doxygen comment](https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_sync/include/hardware/sync.h#L302) which means that it doesn't appear at https://raspberrypi.github.io/pico-sdk-doxygen/index.html .

**Comment by kilograham** [comment]
merged
