### ISSUE TITLE
Enable I2C slave clock stretch by default?

### ISSUE THREAD

**Issue by reynoldsbd** [raspberrypi/pico-sdk#456]
I am using the RP2040 as an I2C slave, but it took quite a bit of trial and error before I realized that clock stretching is not enabled by default.

Would it make sense to set `IC_CON.RX_FIFO_FULL_HLD_CTRL` to 1 by default as part of `i2c_set_slave_mode`?

**Comment by reynoldsbd** [comment]
To be clear, I'm happy to open a PR to make the change myself! I just wanted to touch base here first in case there's some specific reason for the current behavior.

**Comment by Wren6991** [comment]
I think this makes a lot of sense
