### ISSUE TITLE
Incorrect attribute for structure member of SysTick registers

### ISSUE THREAD

**Issue by djrose80** [raspberrypi/pico-sdk#46]
Looking at the file src/rp2040/hardware_structs/include/hardware/structs/systick.h

The member cvr is of type io_ro_32 but it is a read/write register (as detailed in section 2.4.8 of rp2040-datasheet.pdf, and general Cortex M0 literature).

**Comment by lurch** [comment]
@kilograham It's correctly marked as RW in https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2040/hardware_regs/include/hardware/regs/m0plus.h#L106 so I guess this is just a typo in https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2040/hardware_structs/include/hardware/structs/systick.h#L16 ?

**Comment by lurch** [comment]
Seems that this was fixed by #91 so I guess this can be closed?
