### ISSUE TITLE
SDK 1.2.0 - Wattributes

### ISSUE THREAD

**Issue by Wiz-IO** [raspberrypi/pico-sdk#477]
hardware headers
warning: always_inline function might not be inlinable [-Wattributes]
over 200 warninds...

**Comment by kilograham** [comment]
compiler, flags, what are you compiling etc.

**Comment by Wiz-IO** [comment]
I set -Wno-attributes

all is here
https://github.com/Wiz-IO/wizio-pico/blob/main/builder/frameworks/common.py#L149
