### ISSUE TITLE
Using __STATIC_FORCEINLINE coming with cmsis_compiler.h brings extra portability 

### ISSUE THREAD

**Issue by GorgonMeducer** [raspberrypi/pico-sdk#511]
Hi,

I am starting porting pico-sdk to arm compiler 6, and I notice that:

- pico-sdk uses cmsis
- pico-sdk uses **_\_\_force\_inline_** (and always together with static)

So, how about use **\_\_STATIC\_FORCEINLINE** provided by CMSIS (and it supports GCC, LLVM, IAR, AC5 and AC6) to gain better portability? 

or maybe you don't have to change each of the **_\_\_force\_inline_** into **\_\_STATIC\_FORCEINLINE** but simply define it as **\_\_STATIC\_FORCEINLINE** in platform.h

It is just a suggestion.

**Comment by lurch** [comment]
IIRC pico-sdk _optionally_ uses cmsis?

**Comment by GorgonMeducer** [comment]
I am not sure. But use it could bring some cross-platform benefits.

**Comment by kilograham** [comment]
Yeah we won't be using the CMSIS headers directly.
