### ISSUE TITLE
Minimum CMake version needs to be incremented

### ISSUE THREAD

**Issue by philipstarkey** [raspberrypi/pico-sdk#53]
The readme indicates that cmake v3.12 is required at a minimum. This seems to be incorrect, as I get the following error when configuring cmake for the pico-examples repository:

```
[cmake] CMake Error at pico-sdk/src/rp2_common/boot_stage2/CMakeLists.txt:24 (target_link_options):
[cmake]   Unknown CMake command "target_link_options".
```

The [documentation for cmake](https://cmake.org/cmake/help/latest/command/target_link_options.html) indicates `target_link_options` was added in v3.13. I suggest updating the readme and value in `cmake_minimum_required` (probably also in the pico-examples repo as well as here). The SDK/getting started PDF's might also need updating.

FYI, platform is Windows 10 but I don't think that matters as the cmake docs are pretty clear this was added in 3.13.

I also haven't yet tested with v3.13 explicitly, so I can't discount other things requiring an even higher version!

**Comment by Wren6991** [comment]
Thanks, should be fixed by #61
