### ISSUE TITLE
Feature Request: function call when there is input available on stdin

### ISSUE THREAD

**Issue by carlk3** [raspberrypi/pico-sdk#547]
I'm working with the FreeRTOS port, and finding it difficult to use standard input (stdin) from a terminal. Polling stdin with `getchar_timeout_us()` either stalls or burns up all the CPU cycles, which doesn't play well in a multitasking OS. I can see how to make a UART-connected terminal work in an interrupt-driven fashion in `pico-examples/uart/uart_advanced`. However, I would like to maintain the ability to change the destination for stdin and stdout using CMake directives, with input/output directed to UART or USB CDC. 

How about an enhancement to *Serial input and output on Raspberry Pi Pico* that would make it possible to register a callback or something that could receive keystrokes from a terminal as they are typed, asynchronously, regardless of whether serial input (stdin) and output (stdout) are directed to either serial UART or to USB CDC (USB serial)?

**Comment by kilograham** [comment]
merged into develop
