### ISSUE TITLE
Immediate PIO execution ignores delay cycles

### ISSUE THREAD

**Issue by rhulme** [raspberrypi/pico-sdk#570]
It appears from my tests that any delay cycles on an instruction executed via writing to `SMx_INSTR` (or indirectly via `pio_sm_exec`) are ignored.

Maybe this could be explicitly mentioned in the documentation?  Also perhaps for `pio_sm_exec_wait_blocking` as my assumption was that "_wait for it to complete_" meant it wouldn't return until the delay cycles had also elapsed.  Obviously if they're not processed, the instruction will complete immediately (if it doesn't stall on a FIFO or IRQ) but it took quite a bit of investigation to understand what was happening.

**Comment by kilograham** [comment]
It is documented in section 3.5.7 of the data sheet
