### ISSUE TITLE
Possible typo in structs/dma.h

### ISSUE THREAD

**Issue by lurch** [raspberrypi/pico-sdk#582]
https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2040/hardware_structs/include/hardware/structs/dma.h#L55 (which is hand-edited) says `ctrdeq`, but looking at https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2040/hardware_regs/include/hardware/regs/dma.h#L5049 (which is auto-generated) it seems like it _should_ have been named `ctdreq` ?

Although this looks like a simple typo, perhaps the fact that this has ended up in a "public header" means that it's now too late to fix this? :confused:  (If this is a "wontfix", feel free to close this issue)

**Comment by kilograham** [comment]
yeah too late to fix this really
