### ISSUE TITLE
Error compiling rp2_common/hardware_irq/irq.c

### ISSUE THREAD

**Issue by SiliconWizard** [raspberrypi/pico-sdk#597]
Using GCC 10.3.0 (arm-none-eabi), compiling the source file rp2_common/hardware_irq/irq.c yields an error:
> Assembler messages:
> Error: invalid offset, value too big (0x0000040C)

The culprit is the function slot_diff(), which implements pointer difference in inline assembly. I could pinpoint the problematic instruction being "ldr  %0, =0xaaaa\n".

I'm not proficient enough in ARM Cortex assembly to judge, but it looks like this offset would be too large for a LDR instruction on a Cortex-M0/+. Not sure why it would fail to assemble in my case, and apparently not for you guys.

I'd also like to understand the statement in the comment:
> GCC produces horrible code for subtraction of pointers here, and it was bugging me

How horrible could have it been really?

**Comment by kilograham** [comment]
> How horrible could have it been really?

pretty odious, and enough for me to want to change it when it is inlined a bunch

I also tried on 10.3-2021.07 and that seem fine. either way it seems like a compiler bug, however this is equivalent and maybe will help

```

    int32_t result = 0xaaaa;
    // return (to - from);
    // note this implementation has limited range, but is fine for plenty more than -128->127 result
    asm (".syntax unified\n"
         "subs %1, %2\n"
         "adcs %1, %1\n" // * 2 (and + 1 if negative for rounding)
         "muls %0, %1\n"
         "lsrs %0, 20\n"
        : "+l" (result), "+l" (to)
        : "l" (from)
        :
        );
```

**Comment by kilograham** [comment]
yeah it is weird because `ldr , =` is an assembler thing, so the assembler gets to pick where to put the data, so doesn't usually put it somewhere it won't work!

**Comment by kilograham** [comment]
ah actually now i give it a moment's thought it may be a question of `.ltor` placement, so perhaps not to blame the compiler/assembler entirely.

**Comment by SiliconWizard** [comment]
OK, glad I could "help" improve this.

Now I have experience with Cortex-M4 and -M7, but none with -M0/+, and I realized that the latter don't have any hardware divider. I suppose the inefficient code produced by the compiler is due to an inefficient software implementation of division here.

I guess GCC is better at producing efficient code for constant dividers for some dividers and less for others. Here we have a division by 12. AFAIR, divisions by 10 were handled efficiently by GCC - actually generating something similar to your assembly. But that may depend on the divider and on versions of GCC, regressions are not uncommon.

**Comment by kilograham** [comment]
yeah, it is probably also doing a multiply by reciprocal also, however the big failing in GCC on CortexM0+ is there is no way to tell it you have 1 cycle multiply (which RP2040 does), so it insists on doing a serious of shifts and adds.
