### ISSUE TITLE
core1 takes over 100us to start executing code using multicore_launch_core1()

### ISSUE THREAD

**Issue by SiliconWizard** [raspberrypi/pico-sdk#606]
Testing the 'multicore_runner_queue' example, I found out that calling multicore_launch_core1(), it seems to take over 100µs for core1 to actually start executing the code in the entry function passed as an argument.

I'm not saying this is a bug or an issue - but I wanted to know if that was "normal", as I could not find this documented. I think this could be interesting to know.

**Comment by kilograham** [comment]
most of this is because you are running from flash and none of that code path is going to be in the cache on first use (you can build using `no_flash` to confirm).

That said I did notice one function which could be optimized which took it down to about 40us from flash

**Comment by kilograham** [comment]
merged into develop
