### ISSUE TITLE
[question] gpio glitch filtering?

### ISSUE THREAD

**Issue by smdjeff** [raspberrypi/pico-sdk#607]
I'm porting from a Pi to Pico. I use gpioGlitchFilter() from PiGpio C lib for input filtering. It's defined as follows: "Level changes on the GPIO are not reported unless the level has been stable for at least steady microseconds. The level is then reported. Level changes of less than steady microseconds are ignored."

Any plans to support debounce in the pico gpio api? It's unclear how such a thing could be accomplished with the Pico Library as is, because pico timers support only ms resolution at best and even then you'd have to get really busy polling the pins for a "steady state" in microseconds!

**Comment by lurch** [comment]
Is any of the discussion in #141 helpful?

**Comment by kilograham** [comment]
> because pico timers support only ms resolution

not sure where you got that, all the timer APIs support microseconds
