### ISSUE TITLE
occasional weirdness with not connecting over stdio USB when calling getchar and sscanf

### ISSUE THREAD

**Issue by kilograham** [raspberrypi/pico-sdk#623]
see #575  and https://forums.raspberrypi.com/viewtopic.php?f=145&t=321326

**Comment by lurch** [comment]
Just having read that forum thread and #575 again, is it possible that some USB hosts are just "slow" to enumerate, and so the increased sleep-time in #575 gives these "slow" USB ports an increased chance of being able to enumerate the Pico in time? :shrug:  (that's just a random guess, I know very little about USB)

Any thoughts from @P33M ? (who I believe has intimate knowledge of the Linux USB drivers)

**Comment by kilograham** [comment]
likely fixed by #918

**Comment by kilograham** [comment]
closing due to #918 being merged into develop
