### ISSUE TITLE
rp2040.svd file contains an error: Unable to parse SVD file: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by gesture1968** [raspberrypi/pico-sdk#629]
There seems to be an error in the rp2040.svd file. In Platformio during SWD debugging using a cmsis-daplink adapter I get the following error: **Unable to parse SVD file: TypeError: Cannot read property '0' of undefined**. I've started to remove parts of the svd file in order to try and figure out where the error occurs, but I'm not sure if I can find it...

**Comment by zhora6** [comment]
You can try removing undefined elements (in this case 'description') from the svd file like this:

```
sed -i -e '/<description\/>/d' rp2040.svd
```

We ran into this with code [we use to extract equates from svd files](https://github.com/anarchitech/equatesinator).

**Comment by gesture1968** [comment]
@zhora6 : Thanks for your time, but as far as I can see there are no elements that are undefined. But I do have a feeling it is SVD related, as this should be parsed correctly by the openocd in platformio. Still no response on the platformio issues site...

**Comment by JustAnother1** [comment]
There is a validated SVD file for the RP2040 available for [download](https://chipselect.org/Raspberry%20Pi--RP2040.svd)

If there is still an issue with the file you can contact me directly [info@chipselect.org](mailto:info@chipselect.org)

File also attached:
[RP2040.svd.zip](https://github.com/raspberrypi/pico-sdk/files/9977039/RP2040.svd.zip) (compressed as github does not accept *.svd as attachment)

**Comment by kilograham** [comment]
please re-open if this is still an issue
