### ISSUE TITLE
Duplicate struct in header files

### ISSUE THREAD

**Issue by lurch** [raspberrypi/pico-sdk#640]
[`hardware/structs/iobank0.h`](https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2040/hardware_structs/include/hardware/structs/iobank0.h) and [`hardware/structs/ioqspi.h`](https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2040/hardware_structs/include/hardware/structs/ioqspi.h) (which are autogenerated) both contain a struct named `io_status_ctrl_hw_t`. This means if you try `#include`-ing both of these headers as the same time, the compilation fails with:
```
error: conflicting types for 'io_status_ctrl_hw_t'
```

I guess this is something that we should try to fix for SDK 1.3.0 ?

**Comment by kilograham** [comment]
merged into develop
