### ISSUE TITLE
Misleading hint when tinyusb submodule not present

### ISSUE THREAD

**Issue by mancaus** [raspberrypi/pico-sdk#65]
1. Clone sdk
2. Clone examples
3. Set path to sdk and configure CMake to build examples per instructions
4. CMake shows warning:
```
TinyUSB submodule has not been initialized; USB support will be unavailable
--
11 | hint: try 'git submodule update --init'.
```
5. Run `git submodule update -- init` per hint. (no errors displayed)
6. Re-run `cmake ..`

Expected result: tinyusb is available and examples built.
Actual result: tinyusb is not available.

When building a project it's not clear at first glance that the hint's command must be run in the sdk repository. If building the examples, it's reasonable to assume the tinyusb dependency should be bundled with the project, so it's easy to miss even for experienced users :).

Forum post with the same issue: https://www.raspberrypi.org/forums/viewtopic.php?f=144&t=301092#p1808695

Suggest `hint: try 'git submodule update --init' from the pico-sdk git repository`.

**Comment by kilograham** [comment]
merged into develop
