### ISSUE TITLE
PICO_SDK_PATH must be specified for flash boot

### ISSUE THREAD

**Issue by malek-luky** [raspberrypi/pico-sdk#662]
I have trouble running $make V=1 (the third step in Installation from README). I am using Ubuntu LTS 20.04 WSL2 on Windows 10. I would be grateful for any help.

![image](https://user-images.githubusercontent.com/64593628/142177440-3b58e969-ca78-4c0f-a776-3d8c7cec4821.png)

Thank you very much in advance.

**Comment by lurch** [comment]
I don't believe that error message isn't coming from `pico-sdk` - perhaps it's a problem with "nuttx" ? :man_shrugging:

**Comment by aallan** [comment]
If you're installing the SDK on Windows you might want to look at this [third-party installer](https://github.com/ndabas/pico-setup-windows) which simplifies things quite a bit.

**Comment by malek-luky** [comment]
Thank you both for your comments. I am installing the SDK on WSL2, and also building and compiling the code there. I have found the line of code where the problem happens.

![image](https://user-images.githubusercontent.com/64593628/142176000-46788cf8-29a2-4bdb-a129-1d22ae66c423.png)

Unfortunately, I still can't figure out the main reason, because the PICO_SDK_PATH should be correct. A picture from the same terminal window is below.

![image](https://user-images.githubusercontent.com/64593628/142176325-45fa50d2-b6c4-4f30-93eb-e8440e490b40.png)

**Comment by lurch** [comment]
Again, that's code that comes from an external repo, so you'll need to open an issue there.

**Comment by aallan** [comment]
Oh. Sorry, but there is no official support for installing the SDK under Windows Subsystem for Linux at this time. Our official installation route for users running Windows is using the Windows native instructions in Chapter 9 of the [Getting Started](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf) book. This is the method the [third-party installer](https://github.com/ndabas/pico-setup-windows) I mentioned above takes.
