### ISSUE TITLE
incorrect reference to cmake pico_enable functions 

### ISSUE THREAD

**Issue by nitrologic** [raspberrypi/pico-sdk#697]
An incorrect reference to function pico_enable_stdio_usb that takes two parameters (TARGET ENABLE)

https://github.com/raspberrypi/pico-sdk/blob/2062372d203b372849d573f252cf7c6dc2800c0a/src/rp2_common/pico_stdio_usb/include/pico/stdio_usb.h#L16

The same pattern is repeated in stdio_semihosting.h and stdio_uart.h

**Comment by lurch** [comment]
I'm not quite sure what you're asking for, but see "4.1. Serial input and output on Raspberry Pi Pico" in https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf

**Comment by nitrologic** [comment]
This issue affects the helpfulness of c/c++sdk  4.4.20. pico_stdio_usb section in which the ENABLE parameter is omitted from docs generated from line highlighted.

**Comment by lurch** [comment]
Thanks, see #705

**Comment by kilograham** [comment]
this was fixed in 1.3.1
