### ISSUE TITLE
Move (or copy ?) set_sys_clock_khz() from stdlib to clocks.h

### ISSUE THREAD

**Issue by MikeDB1** [raspberrypi/pico-sdk#712]
I would like to not include stdlib but for some reason set_sys_clock_khz() is only present in it.  Moving or copying this function that most people need to clocks.h would allow stdlib not to be included.  Kilograham agreed this would be a good idea.

**Comment by kilograham** [comment]
yes, this code is definitely in the wrong place

**Comment by kilograham** [comment]
fixed
