### ISSUE TITLE
gpio.h should include iobank0.h

### ISSUE THREAD

**Issue by WestfW** [raspberrypi/pico-sdk#733]
If the intention is that `#include <hardware/periph.h>` should end up including all of the info to access `periph` at any of sdk, structure, or individual register level (as mentioned here: https://forums.raspberrypi.com/viewtopic.php?t=329937#p1975241 ), then **hardware/gpio.h** needs to **include the hardware/structs/iobank0.h** and **hardware/regs/io_bank0.h** to be able to reference things like `iobank0_hw->intr[0]`

https://forums.raspberrypi.com/viewtopic.php?p=1974871#p1974871
https://forums.raspberrypi.com/viewtopic.php?p=1975914#p1975814

(and why does one of those filenames have an underscore, and one not?)

**Comment by kilograham** [comment]
merged into develop
