### ISSUE TITLE
pad_checksum doesn't accept 252 byte boot loaders

### ISSUE THREAD

**Issue by Kristine1975** [raspberrypi/pico-sdk#740]
`pad_checksum` pads a stage 2 bootloader to 252 bytes and then appends the checksum. However, if the bootloader already is 252 bytes, it exits with an error. This is due to the following check:

https://github.com/raspberrypi/pico-sdk/blob/2062372d203b372849d573f252cf7c6dc2800c0a/src/rp2_common/boot_stage2/pad_checksum#L34

Unless there is a reason to reject a 252 byte bootloader, I propose to change the check to `if len(idata) > args.pad - 4:`

**Comment by kilograham** [comment]
you fancy submitting a PR ;-)

**Comment by Kristine1975** [comment]
Sorry, I changed my github notifications and accidentally turned them off for this issue. Otherwise I'd have submitted a PR. Thank you for the fix, @lurch!

**Comment by lurch** [comment]
@Kristine1975 I'm happy to close my PR and let you submit one, if you'd like to take the credit yourself?
