### ISSUE TITLE
tinyusb issue

### ISSUE THREAD

**Issue by Nedemai** [raspberrypi/pico-sdk#742]
TinyUSB Host CDC MSC HID Example
assertion "ep->active" failed: file "C:\pico-sdk\lib\tinyusb\src\portable\raspberrypi\rp2040\hcd_rp2040.c", line 164, function: hw_trans_complete

I updated the SDK this morning and started getting this issue. Happens with any USB device I plug in, whether it be a mouse, keyboard or gamepad.

**Comment by kilograham** [comment]
the bug is in TinyUSB... i think you can workaround it for now by switching to a release build (or removing the offending assert)

**Comment by Nedemai** [comment]
As far as I understand I am using a release build.

**Comment by kilograham** [comment]
well assert is a no-op in release builds (which define preprocessor variable `NDEBUG`)

**Comment by kilograham** [comment]
If you aren't using an IDE, then make sure you pass `-DCMAKE_BUILD_TYPE=Release` to cmake
