### ISSUE TITLE
Threads on each Core?

### ISSUE THREAD

**Issue by nsk126** [raspberrypi/pico-sdk#749]
Is it possible to run multiple threads on each core? (Isolated)

Like 3 task threads on Core 0 and 2 threads on Core 1, all handling different assignments.

**Comment by kilograham** [comment]
Yes it is possible; but there is no support for that in the SDK...

Many people use FreeRTOS which has an RP2040 port https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/main/portable/ThirdParty/GCC/RP2040
