### ISSUE TITLE
No support for SEGGER RTT STDIO

### ISSUE THREAD

**Issue by anaoum** [raspberrypi/pico-sdk#774]
It would be nice to be able to use SEGGER RTT as an STDIO driver in the the pico-sdk.

The main advantages of RTT over semihosting are the speed of data transfer and not halting execution.

RTT is widely used and even has support in OpenOCD.

**Comment by peterharperuk** [comment]
Closing this as it's been done. Add the following to your cmake file...

```
pico_enable_stdio_rtt(hello_serial 1)
```

Or change the default.

```
cmake .. -DPICO_STDIO_RTT=1 -DPICO_STDIO_UART=0
```
