### ISSUE TITLE
Add is_end_of_time()

### ISSUE THREAD

**Issue by bruelltuete** [raspberrypi/pico-sdk#783]
We've got a helper function `called is_nil_time()` already.
Lets add `is_end_of_time()` or `is_at_the_end_of_time()` to do the same equivalent check.

happy to open a pr for it.

**Comment by lurch** [comment]
Have you got an example use-case for `is_at_the_end_of_time()` ? Do you have a TARDIS?? :rofl:

**Comment by kilograham** [comment]
merged into develop
