### ISSUE TITLE
 watchdog_caused_reboot() not working correctly?

### ISSUE THREAD

**Issue by tjko** [raspberrypi/pico-sdk#790]
I just happened to notice that _watchdog_caused_reboot()_ returns _true_ after Pico has been reset with openocd (using picoprobe), if Pico has been reset previously by the watchdog. This doesn't seem correct behavior?

Is this perhaps a bug? Or is openocd doing something 'weird' when it resets Pico?

```
openocd -f interface/picoprobe.cfg -f target/rp2040.cfg -c "program build/program.elf verify reset exit"
```

**Comment by kilograham** [comment]
Yes, openocd reset the cores individually, not the whole chip, and thus the watchdog reason does not get cleared.
