### ISSUE TITLE
USB Host Mass Storage Device

### ISSUE THREAD

**Issue by BabumonGopi** [raspberrypi/pico-sdk#791]
Any working program for Mass Storage Device working with pico-sdk ? I had tried to connect with TinyUSB, but it will not working for pico. The following error is coming.

assertion "ep" failed: file "/Users/babumongopi/r-pi/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040/hcd_rp2040.c", line 492, function: hcd_edpt_xfer

Any solution ?

**Comment by mimoccc** [comment]
The best examples are in tinyusb library i think.
Look up for lun msc code there.
That example works perfectly.

**Comment by mimoccc** [comment]
Here: https://github.com/hathach/tinyusb/tree/master/examples/device/cdc_msc
And here: https://github.com/hathach/tinyusb/tree/master/examples/device/msc_dual_lun

**Comment by lurch** [comment]
ping @hathach

**Comment by hathach** [comment]
bulk endpoint for host on rp2040 is not supported yet. Please wait until it is implemented

**Comment by BabumonGopi** [comment]
Is it the issue of RP2040 microcontroller itself or TinyUSB library ?


Babumon Gopi

Poornasree Equipments
www.poornasree.com

**Comment by hathach** [comment]
there is no issue with either rp2040 or TinyUSB. There is only issue with time or lack of it.

**Comment by kilograham** [comment]
Bumping to 1.4.0 to review when we update TinyUSB

**Comment by BabumonGopi** [comment]
Any update ?

**Comment by kilograham** [comment]
@liamfraser can you move this into 1.5.0 if it is fixed with latest TinyUSB

**Comment by kilograham** [comment]
see `tinyusb_host_msc_file_explorer` in pico-examples (example from TinyUSB [here](https://github.com/hathach/tinyusb/tree/master/examples/host/msc_file_explorer)
