### ISSUE TITLE
stdio_set_driver_enabled(.., false) misbehaves if there is only 1 driver

### ISSUE THREAD

**Issue by bruelltuete** [raspberrypi/pico-sdk#808]
When there's one stdio driver registered (e.g. stdio_uart), calling `stdio_set_driver_enabled(..., false)` to disable it breaks the linked list represented by https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_stdio/stdio.c#L32: the head of the list (`drivers`) will continue pointing to the just disabled driver.
see https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/pico_stdio/stdio.c#L182

**Comment by kilograham** [comment]
merged into develop
