### ISSUE TITLE
Include ehaders pot pulling their prerequisites

### ISSUE THREAD

**Issue by smurfix** [raspberrypi/pico-sdk#815]
```
[ 16%] Building C object lib/CMakeFiles/piocan.dir/pico-can.c.obj
In file included from /home/smurf/src/moat-bus/hw/pi/lib/pico-can.c:7:
/home/smurf/src/moat-bus/hw/pi/lib/include/pico-can.h:21:5: error: unknown type name 'uint8_t'
   21 |     uint8_t bits[(CAN_MAX_BITS+7)/8];
      |     ^~~~~~~
```
Umm, IMHO any library header should `#include` the headers it requires in order to work. `<inttypes.h>` in this case.

A patch that adds these will, I hope, be accepted …?

**Comment by lurch** [comment]
Huh? AFAIK `pico-can.h` is nothing to do with Raspberry Pi Pico SDK? :confused:

**Comment by smurfix** [comment]
Owch. Wrong include.
