### ISSUE TITLE
Upgrade TinyUSB

### ISSUE THREAD

**Issue by kilograham** [raspberrypi/pico-sdk#820]
This will land in 1.4.0 not 1.3.x as there may be minor incompatibilities (if major we should consider 2.x)

At this point we should undo #819

**Comment by kilograham** [comment]
see also #1044

**Comment by lurch** [comment]
I guess when this does happen, we'll also want to update the USB examples in [pico-examples](https://github.com/raspberrypi/pico-examples) too? (and also update the pico-examples README.md to mention any new USB examples that get added)

**Comment by kilograham** [comment]
merged into develop

**Comment by lurch** [comment]
> (and also update the pico-examples README.md to mention any new USB examples that get added)

**bump** :wink: 

In #791 @kilograham pointed to the `tinyusb_host_msc_file_explorer` example, but that's not mentioned at https://github.com/raspberrypi/pico-examples#usb-host even though it is listed at https://github.com/hathach/tinyusb/tree/master/examples/host . In fact it looks like _all_ the USB host examples there _do_ include `mcu:RP2040` in their `only.txt` files?

**Comment by kilograham** [comment]
well, i didn't re-read all the comments as the title was quite explicit ;-)
