### ISSUE TITLE
PIOASM_EXTRA_SOURCE_FILES is not passed through to the sub-cmake

### ISSUE THREAD

**Issue by Ferdi265** [raspberrypi/pico-sdk#827]
The PIOASM_EXTRA_SOURCE_FILES variable is not passed through to the inner CMake call, leading to it being impossible to extend `pioasm` from the outside.

This could be desirable for people who want to extend `pioasm` with additional generators (since those can be added without editing existing source files).

**Comment by kilograham** [comment]
merged into develop
