### ISSUE TITLE
"Always true" comparison

### ISSUE THREAD

**Issue by mattgodbolt** [raspberrypi/pico-sdk#83]
With warnings on, gcc will complain that:

https://github.com/raspberrypi/pico-sdk/blob/2d5789eca89658a7f0a01e2d6010c0f254605d72/src/rp2_common/hardware_sync/sync.c#L25

```
error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
   25 |     assert(lock_num >= 0 && lock_num < NUM_SPIN_LOCKS);
```

which is indeed true. Perhaps a _little_ picky, but by definition the unsigned parameter `lock_num` is `>= 0`.

Ditto in `lock_core.c:10`

**Comment by kilograham** [comment]
true dat... i think at one point these were signed!

**Comment by kilograham** [comment]
merged into develop
