### ISSUE TITLE
getchar_timeout_us sleeps 1 µs even when timeout is 0.

### ISSUE THREAD

**Issue by FunMiles** [raspberrypi/pico-sdk#845]
A call such as:
```c
   char c = getchar_timeout_us(0);
```
ends up [in a busy loop for 1µs](https://github.com/raspberrypi/pico-sdk/blob/426e46126b5a1efaea4544cdb71ab81b61983034/src/rp2_common/pico_stdio/stdio.c#L136) even though the timeout is 0.

A check of 0 timeout with a quick exit should precede that line.

**Comment by kilograham** [comment]
merged into develop
