### ISSUE TITLE
Usb assertion "hw_data_offset(next_buffer_ptr) <= USB_DPRAM_MAX"

### ISSUE THREAD

**Issue by ndinsmore** [raspberrypi/pico-sdk#85]
This is a duplicate of the issue I created at please see the issue there for sull documentation:
hathach/tinyusb/issues/628

In the issue I created in the tinyusb repo I mention that I am using the new code coming directly from that repo, but the code at that is at issue is in the SDK tiny USB repo as well.

**Comment by lurch** [comment]
Sounds like something @liamfraser needs to look at?

**Comment by ndinsmore** [comment]
This issue is fixed by hathach/tinyusb#642 @liamfraser it is one real line of code so it should be easy for you to take a look at.

**Comment by liamfraser** [comment]
Looks like a plausible fix to me. I think the audio example may be the first one that repeatedly opens and closes an ep which is why we didn't see this?

**Comment by liamfraser** [comment]
(I don't own the upstream tinyusb repo so I can't merge the PR)

**Comment by hathach** [comment]
@liamfraser please accept my contributor invitation, and feel free to review, approval and merge any PRs that make sense to you. I still haven't got into the usb specs of rp2040 yet. Worse I am on vacation just now :wink:

**Comment by liamfraser** [comment]
@ndinsmore I have merged this into tinyusb upstream

**Comment by liamfraser** [comment]
Will keep this open until either a) our sdk tracks upstream or b) we pick this commit into our fork. We need to review what changes have been made in tinyusb upstream before switching the SDK to it.

**Comment by kilograham** [comment]
closing in favor of #161

**Comment by kilograham** [comment]
changed my mind, will get closed with #321

**Comment by kilograham** [comment]
actually closed by #462

**Comment by kilograham** [comment]
released
