### ISSUE TITLE
Dual slope pwm

### ISSUE THREAD

**Issue by arturohernandez10** [raspberrypi/pico-sdk#861]
When driving a motor a dual slope pwm is very important.  And it is supported by other cortex-m0  controllers. Is it just missing from the SDK, can a pwm slice be connected to a gpio state machine and produce a dual slope pwm that way?

**Comment by JamesH65** [comment]
Is this what we called phase correct mode? 4.5.2.1. Pulse Width Modulation in https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf

**Comment by kilograham** [comment]
closing this question
