### ISSUE TITLE
Issue with macro in `pico/binary_info.h`

### ISSUE THREAD

**Issue by infovore** [raspberrypi/pico-sdk#867]
This caused my project to stop compiling:

My code includes `pico/binary_info.h`; when I include this line of code, however:

```
bi_decl(
      bi_3pins_with_func(SPI_RX_PIN, SPI_TX_PIN, SPI_SCK_PIN, GPIO_FUNC_SPI)
);
```

(which tells the BI about my SPI configuration, I believe)

the build fails with this message:

```
[build] /Users/ME/src/pico-sdk/src/common/pico_binary_info/include/pico/binary_info/code.h:22:55: error: '_error_bi_is_missing_enclosing_decl_93' was not declared in this scope; did you mean '_error_bi_is_missing_enclosing_decl_92'?
```

That line of code uses a macro that embeds the `__LINE__` number, and clearly it's being calculated wrong, and I have _no idea_ why - I'm not a super experienced C++ programmer.

This happens with `arm-none-eabi` 9.21 and 7.2.1, and I'm using CMake 3.23.2.

Any ideas?

**Comment by lurch** [comment]
Looking at https://github.com/raspberrypi/pico-examples/search?q=bi_3pins_with_func&type=code I wonder if your error might be caused by your `bi_decl` and `bi_3pins_with_func` being on different lines? That's a bit of a random guess though :wink:

**Comment by infovore** [comment]
@lurch oh good lord. that is, in fact, the funkiness at my end. Of course: what puzzles me is that this used to compile. Anyhow, mystery solved, let's close this and never talk of it again.
