### ISSUE TITLE
Issue with reset interface with new stdio over use TinyUSB support

### ISSUE THREAD

**Issue by kilograham** [raspberrypi/pico-sdk#892]
https://forums.raspberrypi.com/viewtopic.php?t=334842

**Comment by MattMills** [comment]
Just as an FYI for anyone finding this issue, I wrote my own code to do STDIO via USB, plus CDC (serial) port forwarding for uart0 and uart1 on rp, + USB Mass storage for flashing an RP2040 or an attached ESP32 via uart0 here: https://github.com/2bn-dev/tinyusb_multitool

Probably not as nice as whatever the Raspberry pi team will put together though, as my C is kind of rough.

**Comment by kilograham** [comment]
This is now possible

**Comment by svofski** [comment]
I'm sorry, but I don't see how can I enable this? I have created a composite device with TinyUSB CDC and MIDI. I can send midi messages and printf() to CDC serial port, but I cannot reset using `picotool reboot -u -f`. How can I enable this function?
