### ISSUE TITLE
README doesn't describe how to target Pico W board

### ISSUE THREAD

**Issue by lbt** [raspberrypi/pico-sdk#895]
Although the pico_w.h board is now present the 'terse' README should probably mention how to target it

**Comment by kilograham** [comment]
which README?

**Comment by lurch** [comment]
Presumably this one? https://github.com/raspberrypi/pico-sdk/blob/master/README.md

@lbt There's more detailed documentation in https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf

**Comment by lbt** [comment]
Thanks - I knew there would be a target :)

I looked at commit https://github.com/raspberrypi/pico-sdk/commit/5e9a5e827b3265fca53529883abdcc87608abad5 and although the top level README.md is extended, none of the docs mention how to target the newly added board and nor do they add the link mentioned above.

I'd think adding a new board and introducing a new concept of NEEDING to target it would be important enough for the high level README ;)

I'll pull together a patch now @lurch pointed me to the correct syntax

**Comment by JamesWP** [comment]
This would have saved me some time too, I've put a comment on the PR to the same effect.

**Comment by MrGreensWorkshop** [comment]
I believe adding to CMakeLists.txt file is better than adding as cmake params.
I prefer to put in CMakeLists.txt file like below
`set(PICO_BOARD pico_w)`

**Comment by kilograham** [comment]
merged into develop
