### ISSUE TITLE
Use rev and rev16 instructions for LWIP ntohl() and nthos()

### ISSUE THREAD

**Issue by slimhazard** [raspberrypi/pico-sdk#913]
One of the ways that the LWIP project recommends optimization for a platform is to provide platform-specific implementations of the byte swap functions. If none are provided, LWIP does it by default with bit twiddling (shifts and ors).

On the RP2040, these can be done in one instruction each with `rev` and `rev16`. PR is on the way.

**Comment by kilograham** [comment]
compiler takes care of this in general
