### ISSUE TITLE
Issue waking up from dormant mode via gpio (active low).

### ISSUE THREAD

**Issue by DatanoiseTV** [raspberrypi/pico-sdk#938]
I am using a nRF24L01+ 2.4GHz transceiver which has an IRQ pin that can fire (active low) when data has been received.
Unfortunately, the RP2040 doesn't wake up properly and therefore I cannot process any packets after it goes to dormant mode.

https://github.com/nRF24/RF24/issues/857

**Comment by 2bndy5** [comment]
This might belong to pico-extras domain because the code uses pico-sleep lib, but I'll let the admin decide.

**Comment by 2bndy5** [comment]
moved to https://github.com/raspberrypi/pico-extras/issues/40
