### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by AssKicker09** [raspberrypi/pico-sdk#944]
Iam trying to compile a software with MQTT messaging. But it failed, because the Mqqt Lib insight the LWIP lib ist not found.

**Comment by lurch** [comment]
This might be a question better suited for the forums? https://forums.raspberrypi.com/viewforum.php?f=143

**Comment by lurch** [comment]
@peter123123 See #948

**Comment by kilograham** [comment]
merged into develop
