### ISSUE TITLE
cyw43_bus_pio_spi.c refers to state machine zero in two places

### ISSUE THREAD

**Issue by rde2** [raspberrypi/pico-sdk#946]
cyw43_spi_init allocates an unused state machine at line 113:

bus_data->pio_sm = (int8_t)pio_claim_unused_sm(bus_data->pio, false);

but later in cyw43_spi_transfer state machine 0 is used to create the DMA DREQs:

channel_config_set_dreq(&out_config, pio_get_dreq(bus_data->pio, **0**, true));
channel_config_set_dreq(&in_config, pio_get_dreq(bus_data->pio, **0**, false));

If other code has already allocated state machine 0, the driver does not work correctly.

**Comment by lurch** [comment]
Are there any places that the not-yet-merged #940 has missed?

**Comment by rde2** [comment]
Looks like a duplicate of #940.  I missed that on, sorry,
