### ISSUE TITLE
A target created by pico_simple_hardware_headers_target should depend on hardware_claim_headers not hardware_claim

### ISSUE THREAD

**Issue by ooxi** [raspberrypi/pico-sdk#957]
A target created by [`pico_simple_hardware_headers_target`](https://github.com/raspberrypi/pico-sdk/blob/master/src/CMakeLists.txt#L59-L72) should depend on `hardware_claim_headers` not `hardware_claim`.

The reason for this change request is `hardware_claim` adding `claim.c` to my sources, which I do not want (otherwise I would have depended on e.g. `hardware_gpio` not `hardware_gpio_headers`).

This is not an issue for `hardware_structs` since this target does not define sources.

**Comment by kilograham** [comment]
Part of #882

**Comment by kilograham** [comment]
fixed
