### ISSUE TITLE
cyw43_arch_threadsafe_background bugs preventing deinit() / init()

### ISSUE THREAD

**Issue by Memotech-Bill** [raspberrypi/pico-sdk#980]
I have code which is linked using the CMake cyw43_arch_threadsafe_background link_library.
The code can call cyw43_arch_init(), cyw43_arch_deinit() and later cyw43_arch_init() again.

The second call to cyw43_arch_init() hangs.

I have found at least two issues which are responsible for this:

* In cyw43_arch_threadsafe_background.c routine cyw43_arch_init() includes the line:

`    gpio_add_raw_irq_handler_with_order_priority(IO_IRQ_BANK0, gpio_irq_handler, CYW43_GPIO_IRQ_HANDLER_PRIORITY);`

  However cyw43_arch_deinit() is missing the corresponding:

`    gpio_remove_raw_irq_handler (IO_IRQ_BANK0, gpio_irq_handler);`

* Secondly, in file cyw43_arch_poll.c, the call to lwip_init() is wrapped in code to ensure that it is called only on the first call to cyw43_arch_init():

```
    static bool done_lwip_init;
    if (!done_lwip_init) {
        lwip_init();
        done_lwip_init = true;
    }
```

  However, the call to lwip_init() in cyw43_arch_threadsafe_background.c is missing a similar wrapper.

**Comment by lurch** [comment]
See also #968 and #969 ?

**Comment by kilograham** [comment]
should be fixed by #1177; please give it a try if you can - i haven't yet tested this particular issue

**Comment by kilograham** [comment]
#1177 merged into develop

**Comment by flaviorenga** [comment]
Hi @Memotech-Bill and all!
I'm working on a Pico 2W project that needs to power cycle the BLE module (init → use → deinit → sleep → wake → init again) for battery saving.

**Questions:**
1. **Was this bug ever fixed** in newer SDK versions? (I'm using SDK 2.2.0)
2. **Is there a working workaround** to safely reinitialize `cyw43_arch` after `deinit()` for BLE use cases?

My current issue: first `cyw43_arch_init()` works, `cyw43_arch_deinit()` completes, but the second `cyw43_arch_init()` hangs.
Any guidance on how to properly handle BLE power cycling on Pico 2W would be greatly appreciated!
Thanks!

**Comment by Memotech-Bill** [comment]
It is a while since I last tried this.

Also the CYW43 code has completely changed since I raised this issue, it now uses the pico/async_context. So any fix of the issue I raised would be irrelevant.

I also note that the current **cyw43_arch_init**  and **cyw43_arch_deinit** routines include code enclosed in CYW43_ENABLE_BLUETOOTH conditionals. Since I am not using Bluetooth I would not test that part of the code anyway.

**Comment by flaviorenga** [comment]
Thank you for your answer!
I solved this issue by implementing a state machine with persistent storage and hard resets between states. This approach ensures clean BLE initialization on every cycle.

**The solution works as follows:**

**State 0 - Data Acquisition:**
- Sample data from ADC
- Process and calculate statistics
- Store results in flash memory
- Update state to 1 in flash
- Enter low-power mode (waiting for interrupt/timer)
- Perform hard reset via watchdog


**State 1 - BLE Transmission:**
- Read stored data from flash memory
- Initialize BLE stack (fresh initialization after reset)
- Advertise and transmit data to client
- Update state to 0 in flash
- Enter low-power mode (waiting for interrupt/timer)
- Perform hard reset via watchdog

This cycle repeats indefinitely.



**Key benefits:**

- Each BLE initialization is clean (no leftover state from previous cycles)
- Hard reset eliminates any potential memory leaks or state corruption
- Flash storage preserves data across resets
- Low power consumption between cycles

The hard reset approach proved more reliable than attempting to deinitialize and reinitialize the CYW43 BLE stack multiple times within the same boot cycle.
